### ISSUE TITLE
Test N5.17 teller feil

### ISSUE THREAD

**Issue by palm72** [arkivverket/arkade5#101]
Funnet i Arkade 5 versjon 1.4.0.0 (og 1.3.2.0)
Test N5.17 – Antall av ulike journalposttyper 
Tester uttrekk hvor en del journalposter er uten dokumentbeskrivelser. Testen rapporterer derfor at disse journalpostene mangler hoveddokument.
Øverst i testrapporten blir de rapportert som avvik: 
        N5.17 – Antall av ulike journalposttyper | 39709
Her er antallet korrekt.

Lenger ned i rapporten listes 100 tilfeller opp før den rapporterer "39637 flere resultater av samme type". 

Ingen stor feil, men det er et avvik på 28 journalposter - avhengig av hvor en ser i rapporten.

**Comment by joergen-vs** [comment]
Grunnet hvordan testen er oppdatert, bortfaller problemstillingen.
