### ISSUE TITLE
Siste bygg (v1.4) av Arkade feiler på tidligere godkjente varianter av Noark5-pakker jeg har i depot

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#103]
Veldig ofte kommer det feil av vedlagte type. Dette gjør at testing ikke kan gå videre. Men feilen sier INGENTING om hva, eller hvor feilen er i XML-filene. Dette MÅ forbedres slik at det kan bli lettere å gå uttrekket i sømmene.

Gi mulighet i alle fall til utvidet logging for de som ønsker det.

Feilmeldingen er av den kryptiske sorten: 

System information:
Arkade version: 1.4.0.0
.NET CLR: 4.0.30319.42000
Total disk space: 480085274624 (457844 MB)
Available disk space: 401928249344 (383308 MB)

Stack trace:
System.NullReferenceException: Objektreferanse er ikke satt til en objektforekomst.
   ved Arkivverket.Arkade.Core.Testing.Noark5.NumberOfClasses.ReadStartElementEvent(Object sender, ReadElementEventArgs eventArgs)
   ved Arkivverket.Arkade.Core.Base.Noark5.Noark5XmlReaderBaseTest.OnReadStartElementEvent(Object sender, ReadElementEventArgs e)
   ved System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   ved Arkivverket.Arkade.Core.Base.Noark5.Noark5TestEngine.RaiseReadStartElementEvent(ReadElementEventArgs readElementEventArgs)
   ved Arkivverket.Arkade.Core.Base.Noark5.Noark5TestEngine.RunContentTests(Archive archive)
   ved Arkivverket.Arkade.Core.Base.Noark5.Noark5TestEngine.RunTestsOnArchive(TestSession testSession)
   ved Arkivverket.Arkade.Core.Base.ArkadeApi.RunTests(TestSession testSession)
   ved Arkivverket.Arkade.GUI.ViewModels.TestRunnerViewModel.RunTests() i C:\dev\TeamCity\buildAgent\work\a0525764e1ed6c7e\src\Arkivverket.Arkade.GUI\ViewModels\TestRunnerViewModel.cs:linje 284

Antar dette har med at det mangler en node i XML'en et sted (tror kanskje det er fordi det mangler klassifikasjonssystem akkurat i dette tilfellet.. fagsystem SOCIO)

**Comment by joergen-vs** [comment]
NumberOfClasses.ReadStartElementEvent kaster en NullReferenceException, og den eneste verdien som kan være null er _currentClassificationSystem. Høres ut som det mangler klassifikasjonssystem i arkivet.

Siden et arkiv kun trenger å ha et klassifikasjonssystem i saksarkiver [hovedmodellen for arkivstruktur], kan det finnes fagsystem-versjoner uten klassifikasjonssystem. Arkade 5 føyer seg i utgangspunktet etter hovedmodellen.

Tar bedre rapportering opp med utviklerne.

**Comment by solfeggietto** [comment]
Arkade 5 bør håndtere arkiver uten et klassifikasjonssystem, altså kunne kjøre validering av at Noark 5-uttrekk av et fagsystem unten klassifikasjonssystem. Valideringer/rapporteringer som krever klassifikasjonssystem kan man da hoppe over når klassifikasjonssystem ikke finnes, men kjøres hvis det finnes i uttrekket. Dette slik at fagsystemer også kan valideres gjennom Arkade 5 sin Noark 5-validering.

**Comment by erikaaberg** [comment]
Forbedret.
