### ISSUE TITLE
Hvor bliver metadata "Uttrekksdato" av?

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#104]
Hvor finner jeg igjen metadata felt "Uttrekksdato" i info.xml (<uuid>.xml) eller i .tar filas innholdselementer?

Har kjørt en test med Fagsystem og fylt ut alle felter, og det er kun "Uttrekksdato" jeg ikke finner igjen i info.xml

**Comment by joergen-vs** [comment]
Uttrekksdato finnes igjen i metsHdr.CREATEDATE;
<metsHdr CREATEDATE="2015-02-28T00:00:00">

**Comment by erikaaberg** [comment]
Antas da løst. Ref. siste kommentar.
