### ISSUE TITLE
Feil info i pressemelding

### ISSUE THREAD

**Issue by AnnKnu** [arkivverket/arkade5#106]
------------------  ---------------------------------
           Prosjekt  Arkade 5
           Kategori  Versjon 1.5.0 
           Dokumentdel  #arkade5/docs/index.rst
 ------------------  ---------------------------------

### Beskrivelse

Pressemelding fra 2017 https://github.com/arkivverket/arkade5/blob/1.5.0/docs/index.rst 
må oppdateres og releases på nytt slik at informasjon på http://arkade.arkivverket.no/no/latest/ blir riktig. 

## Ønsket endring
Oppdater med siste og riktig informasjon

**Comment by joergen-vs** [comment]
Dokumentasjon oppdatert og lagt i eget område.
