### ISSUE TITLE
info.xml validerer ikke mot noen kjente .xsd

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#107]
Hvordan får vi validert mottatt info.xml produsert i Arkade 5 v1.4.0.0 av arkivskaper og innsendt pr. epost til depot? Hverken dias-mets.xsd i AIP pakken, info.xsd fra GitHub Arkade 5 eller submissionDescription.xsd fra Arkivverket GitHUb Shemas validerer korrekt mot info.xml. 

Noen som har master xsd for info.xml?

**Comment by solfeggietto** [comment]
Ser at Arkade 5 v1.5.0.0 er release 22.10.2019 uten at klient v1.4.0.0 varsler om ny versjon...
(sender egen issue på det).

Arkade 5 skjema for info.xml? (oppdatert 12.07.2018)
https://github.com/arkivverket/arkade5/blob/master/src/Arkivverket.Arkade.Core/ExternalModels/xsd/info.xsd

Skjema for mets.xml filer? (oppdatert 22.10.2019)
https://github.com/arkivverket/arkade5/blob/master/src/Arkivverket.Arkade.Core/ExternalModels/xsd/mets.xsd

Arkivverkets infofil (oppdatert 20.09.2019)
https://github.com/arkivverket/schemas/tree/master/INFOFIL/latest

**Comment by joergen-vs** [comment]
Løst i siste versjon, info.xml validerer mot variasjonen av mets.xsd v1.9.1 med bl.a. krav om antall altRecordID:
http://schema.arkivverket.no/INFOFIL/latest/submissionDescription.xsd
http://schema.arkivverket.no/METS/mets.xsd
