### ISSUE TITLE
Håndtering av "autogenererte" datoer f. eks. 0001-01-01T00:00:00

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#109]
Arkade 5 rapport burde utelatt datoer som tydelig er utenfor rimelighetens grenser i sine tellere og rapporteringer.

Eksempel ephorte Noark 5-uttrekk med ephorteSubmision v2.7.1 som setter autogenererte verdier av datoer til 0001-01-01T00:00:00, eller at disse datoene ble satt av Evry i forbindelse Noark 4 til Noark 5 oppgradering av basen.

Som i eksempelet under burke 01.01.0001 avvises og heller vises i en feillogg, mens normale første dato burde vært brukt som startdato i arkivstrukturen.

`
N5.60 – Start- og sluttdatoer 
Type: Innholdsanalyse

Resultater
Lokasjon - Melding
Start- og sluttdato i arkivstrukturen: 01.01.0001 - 17.06.2019 
Start- og sluttdato i offentlig journal: 04.01.2016 - 16.06.2019 
Start- og sluttdato i løpende journal: 04.01.2016 - 16.06.2019 
`

**Comment by joergen-vs** [comment]
Det er ikke planlagt behandling av slike avvik, da det på en eller annen måte må dokumenteres hva som er en dummy-verdi. For noen systemer er standard dato 01.01.1970, mens uttrekksleverandør står fritt til å velge "en dato som er menneskelig gjenkjennelig utenfor perioden", for å vise at det er snakk om data som ikke finnes i opphavsbasen.
Det finnes også tilfeller på menneske- og systemfeil hvor datoen er 1901 eller 1919. Her er det først snakk om å gå fra to tegn i årstall til fire, og glemme at man lever i 21. århundre, og 1919 var tastefeil for 1991.

Inntil videre er det dermed behov for menneskeøyne for å oppdage og dokumentere slike avvik.

**Comment by erikaaberg** [comment]
Skyldes feil i produksjon av uttrekk. Prioriteres ikke av Arkade.
