### ISSUE TITLE
Testene stopper ved feil i validering av XML

### ISSUE THREAD

**Issue by palm72** [arkivverket/arkade5#11]
Ved testing av Noark 5 uttrekk i versjon 0.5.7.0 av Arkade 5. 
For å teste et uttrekk fikk jeg stopp på følgende feil i XML. Hvert punkt krever korrigering av XML og ny kjøring av testverktøyet. Siden testverktøyet låser arkivstruktur.xml, må det avsluttes og startes på nytt for å få lagret korrigert arkivstruktur.xml:

1) Feil datoformat i `<tilknyttetDato />`
2) Skrivefeil i taggen `<referanseSekundaerKlassifikasjon />`
3) Bruk av ugyldige verdier i `<avskrivningsmaate />` (her ble det også forsøkt å korrigere medfølgende XSD)
4) Manglende tagg `<sjekksumAlgoritme />` og `<sjekksum />` (gjelder ødelagte/manglende filer)
5) Manglende tagg `<tittel />` i en dokumentbeskrivelse.
6) Manglende tagg og data `<korrespondansepart />` i 3 registreringer
7) Hadde 2 dupliserte `<sjekksum />` i uttrekket
8) Hadde 3 dupliserte `<sletting />`  i uttrekket
9) Hadde en ugyldig variant av `<variantformat />`
10) Hadde en feilklassert saksmappe.

Dette er dessverre ikke uvanlig mange feil, men 10 kjøringer av verktøyet er i overkant mye.

**Comment by erikaaberg** [comment]
Noen feil gjør det umulig å fortsette, men terskelen for å terminere må heves.

**Comment by erikaaberg** [comment]
I prinsippet løst, men Issue beholdes likevel, da "for mange feil" får programmet til å henge.

**Comment by erikaaberg** [comment]
Dette regnes nå som "godt nok"
