### ISSUE TITLE
Arkivdeler - Mer info

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#110]
Ønske for neste release : 
"N5.05 – Antall arkivdeler" kunne gjerne også listet ut arkivdelene med navn (antar de har det..). I resten av rapporten er det kun henvist til SystemID for arkivdelen, men ingen referanse til hvilken arkivdel det faktisk er for en leser av rapporten.

Enten oppgi en liste over arkivdeler og tilhørende systemid'er eller bytt ut alle steder hvor systemid for arkivdel er oppgitt og oppgi heller navnet på arkivdelen (evt. begge deler..)

Får mye spørsmål rundt "hva er systemid, og hvordan finner jeg ut hvilken arkivdel feilene ligger i?"

**Comment by joergen-vs** [comment]
Arkivdel har tittel, og vi vil gå for noe lignende "systemID - tittel"
