### ISSUE TITLE
Arkade 5 metadata for agent inkonsistent

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#111]
DIAS info.xml blir inkosistent for agent data.
Agent informasjon type "INDIVIDUAL"

Fra Arkade 5 v1.4.0.0 ble adresse innført som metadata for agenter personinfo.
Problemet er der kanskje allerede før dette og har bakgrunn i at unik info kun er på elementet mets:name, mens de 4 underliggende elementer er identifisert med mets:note.

Det føre til at en leser av info.xml ikke unikt kan identifisere hva som er kontaktperson, adresse, telefon og epost av disse, siden alle vel er valgfrie (må sjekkes i skjemaet).

Eksempel der arkivskaper har tomt adressefelt og da får 3 stk. mets:note elementer.
Mens producer bruker alle 4 feltene.
En automatisk lesing av disse data er da i villrede og kan ikke med sikkerhet si hva som er hva.

    <mets:agent ROLE="OTHER" OTHERROLE="SUBMITTER" TYPE="ORGANIZATION">
      <mets:name>Test kommune</mets:name>
    </mets:agent>
    <mets:agent ROLE="OTHER" OTHERROLE="SUBMITTER" TYPE="INDIVIDUAL">
      <mets:name>Per person</mets:name>
      <mets:note>12345678</mets:note>
      <mets:note>per.person@test.kommune.no</mets:note>
    </mets:agent>

    <mets:agent ROLE="OTHER" OTHERROLE="PRODUCER" TYPE="ORGANIZATION">
      <mets:name>Uttrekk IKT</mets:name>
    </mets:agent>
    <mets:agent ROLE="OTHER" OTHERROLE="PRODUCER" TYPE="INDIVIDUAL">
      <mets:name>Audun Automat</mets:name>
      <mets:note>Automatgata 111</mets:note>
      <mets:note>9876543210</mets:note>
      <mets:note>audun.automat@automat.no</mets:note>
    </mets:agent>

**Comment by joergen-vs** [comment]
Det ble først lagt til i siste versjon av mets (amerikanske):
```xml
  <xsd:element name="note" minOccurs="0" maxOccurs="unbounded">
    <xsd:annotation>
      <xsd:documentation xml:lang="en">
      The <note> element can be used to record any additional information regarding the agent's activities with respect to the METS document.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:anyAttribute namespace="##other" processContents="lax"/>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>```

Foreløpig ordner Arkade dette, ved å ha fast antall tomme elementer
![image](https://user-images.githubusercontent.com/10667652/68372321-e6cdc080-0140-11ea-84ce-3f80d7f51514.png)
![image](https://user-images.githubusercontent.com/10667652/68372395-095fd980-0141-11ea-8106-5b1fc172be81.png)

Arkade følger DIAS-standardens verjson av mets, og vil holde seg oppdatert slik at de pakker som lages, kan brukes av langtidslagringsløsningene som implementerer DIAS.

**Comment by solfeggietto** [comment]
Selv om METS ikke åpner for ekstra atributter som kan identifisere hva den enkelte <note> er for agenten (adresse, telefon og epost), så kan defineres en DIAS-spesifikk regel for bruken av disse. Det er ikke nødvendig å understøøte dette med .xsd skjema.

SIARD regel for agent <note>:
1. Det skal være 3 stk. <note> elementer hvis de benyttes
2. Første <note> er person adresse
3. Andre <note> er person telefonnummer
4. Tredje <note> er person epost
5. et <note> element kan være tomt <note /> eller <note></note>

Det må være et <name> element øverst for at bruke av <note> skal gi mening.

**Comment by erikaaberg** [comment]
Problem løst i Arkade versjon 1.6.0 (ref. Jira 408)- et xtra Note attributt i METS.
