### ISSUE TITLE
Failure in N5.60

### ISSUE THREAD

**Issue by douzounov** [arkivverket/arkade5#112]
We validated an extraction package with Arkade and the report stated that:

_"Periodeskille er skarpt og datoer i arkivstrukturen er ikke like de i offentlig og løpende journal."_ 

Arkade determines the time period in offentligJournal.xml/loependeJoural.xml using journalStartDato (M112) and journalSluttDato (M113). Note that the Noark 5.5 metadata catalog states that journalStartDato (M112) "skal selekteres på M101 journaldato", and that journalSluttDato (M113) "skal selekteres på M101 journaldato", so it is logical that journalStartDato (M112) and journalSluttDato (M113) contain values from journaldato (M101).

For some reason Arkade uses opprettetDato (M600) instead of journaldato (M101) when determining the time period in arkivstruktur.xml. The code implementing the test (`Arkivverket.Arkade.Core/Testing/Noark5/N5_60_ArchiveStartAndEndDateControl.cs`) seems to assume that opprettetDato (M600) is always the same as journaldato (M101) for all records, but this is not always the case, which will result in N5.60 reporting nonexistent errors. See the code below:

```
   var archiveDates = new StartAndEndDate(
        _registrationCreationDates.First(),
        _registrationCreationDates.Last()
    );
    var publicJournalDates = new StartAndEndDate(
        headPublicJournal.JournalStartDate,
        headPublicJournal.JournalEndDate
    );
    var runningJournalDates = new StartAndEndDate(
        headRunningJournal.JournalStartDate,
        headRunningJournal.JournalEndDate
    );
```

**If one is to compare the time period in løpende/offentlig journal to the time period in arkivstruktur, one must use the same field! That field must be journaldato (M101), not opprettetDato (M600). The N5.60 test is meaningless by definition if it uses different fields unless those fields always contain the exact same values, which is not the case with opprettetDato (M600) and  journaldato (M101).**

Note that issue https://github.com/arkivverket/arkade5/issues/105 is remotely related to what is described here.

**Comment by joergen-vs** [comment]
Its been reported to the developers.

**Comment by douzounov** [comment]
It appears that the issue is fixed with https://github.com/arkivverket/arkade5/commit/792ab423f5fcf3a69ce30ab6597c10ea2cb0406a. Awaiting an official build of 1.5.1 to test this.
