### ISSUE TITLE
Arkade metadata må trimmes

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#113]
Arkade 5 må trimme data fra inntalstede/importerte feilter, som f. eks. metadata til info.xml, slik at space, tab, linjeskift eller andre  uønskede tegne før og etter feltverdien blir vasket vekk.

Arkade 5 v1.5.0.0 lagrede metadata til info.xml og andre steder i DIAS-pakken legger inn data slik de finnes i GUI-feltene (har ikke testet konsoll-varianten).

Det fører til f. eks.
`<mets:name> Interkommunalt Arkiv for Møre og Romsdal IKS</metsname>`

Her lagt inn med et space først i feltet. Som vi vet tar copy-paste ofte noe med før og/eller etter i GUI-felter.

**Comment by erikaaberg** [comment]
Vi ser på saken - i svært nær fremtid.
