### ISSUE TITLE
Gjenbruk av gammel info.xml gir feil i Arkade 5 v1.5.1.0

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#116]
Korrekt lagret i Arkade 5 v1.5.1.0 skal være altid 4 stk. note til person-agenter:
```
    <mets:agent ROLE="ARCHIVIST" TYPE="INDIVIDUAL">
      <mets:name>Pernille Person</mets:name>
      <mets:note />
      <mets:note />
      <mets:note>pernille.person@test.kommune.no</mets:note>
    </mets:agent>
```

Men hvis man lykkes med å importere en forrige info.xml uten 4 elementer, så gjentas dette i ny produsert Arkade 5 v1.5.1.0 info xml, altså med minre enn 3 mets:note elementer
```
  <mets:agent ROLE="ARCHIVIST" TYPE="INDIVIDUAL">
      <mets:name>Per Person</mets:name>
      <mets:note>12345678</mets:note>
      <mets:note>per.person@test.kommune.no</mets:note>
    </mets:agent>
```

**Comment by solfeggietto** [comment]
Jørgen Tellnes, Arkitektum forklarte saken er en tilfeldighet/et uventet resultat. De tomme <note> kom med pga. en bug og ikke som jeg forventet det. Standard å produksjon av en SIP/AIP pakke i Arkade 5 skaper kun `<note>` elementer for felter som har verdi og er det en tom streng i GUI metadatafeltet, så produseres der altså ikke et `<note>` element.

Det er med andre ord en bug at en importert info.xml som inneholder tomme `<note>` elementer da tar med disse videre i ny produsert info.xml.

Se forøvrig Issue 111 hvor jeg foreslår en regel for at det skal være fast 3 stk. `<note>` hvis elementet er i bruk, for å sikre at info.xml er entydig og vi kan autmatisere lesing av denne i produksjonslinjen.
[https://github.com/arkivverket/arkade5/issues/111])

**Comment by erikaaberg** [comment]
Fixet.
