### ISSUE TITLE
SIP is not saving testresults in \administrative_metadata\repository_operations

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#117]
Poster en Issue som er meldt Arkivverket noen ganger før pr. epost.

### Epost til arkade5@arkivverket.no den 05.12.2017 ####

No når arbeidsområdet til Arkade 5 slettes fra v1.0.5.88, så vil det si at med en gang vi lukker Arkade 5, så vil testresultatene gå tapt.

Arkade 5 er et testverktøy og det er ikke alltid vi vil lage ny SIP/AIP-pakke av et uttrekk vi tester. Dette gjelder i alle fall depot som mottar det deponerte uttrekket og har som hovedarbeidsoppgave å teste og validerer uttrekket iht. den typen det er levert som (Noark 5/4/3, Tabelluttrekk).

Depot kan også måtte teste ulike sider av uttrekket, altså teste det flere ganger. F. eks. teste med å endre xsd-skjemaer på en kopi av et Noark 5 uttrekk for å dokumentere at avvikene på originalen sin feil i validering av xml-filene mot side xsd-skjemaer har spesifikke dokumentert årsaker gjennom en sli test.

Derfor må det være en mulighet for å lagre kun testresultatene, uten å måtta ta med hele uttrekket (som kan være på mange GB)? Kanskje valgene Lag "SIP" / "AIP" / "Testrapport"?

Slik det er no så må brukeren av Arkade 5 v1.0.5.88 manuelt kopiere ut katalogen:
..\Arkade\work\<uuid>\administrative_metadata\
Som har filene arkade-log.xml og report.html
Og det FØR brukeren lukker Arkade 5, med mindre man har laget en AIP fra Arkade 5 (eller seinere når feilen er rettet laget en AIP eller en SIP siden SIP ikke har med disse filene i v1.0.5.88).

**Comment by solfeggietto** [comment]
Arkade 5 v1.6.1 med SIP-pakke inkluderer fortsatt ikke test-resultatene (report.html og arkade-log.xml). Dette bør være enkelt å endre?

![Arkade5_v1 6 1_SIP_vs_AIP](https://user-images.githubusercontent.com/622856/78031626-17b6c800-7364-11ea-9939-7eb66fb71775.png)

**Comment by erikaaberg** [comment]
"Derfor må det være en mulighet for å lagre kun testresultatene, uten å måtta ta med hele uttrekket".
Det er nå mulig.
