### ISSUE TITLE
log-fil er mangelfull på feilmeldinger

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#119]
arkade-log.xml skal ha oversikt over det som skjer i arkade, og blir også med i AIP'en (men ikke i SIP??). Synes det da er rart at antallet feil begrenses til de 100 første, selv om det er stor sjanse for at feil 101->x ikke er lik foregående 100.

Greit nok at arkade-sluttrapporten har begrensning på type feil, men synes det blir feil at ikke arkade-log.xml gjenspeiler faktiske feil som finnes.

Er jo hardkodet noen steder i kildekoden at begrensning skal være 100, så kanskje flytte dette til config-vinduet eller til en config-fil et sted?

Alternativet er at Arkade-rapporten aggregerer feilene og henviser til en liste med linjenummer eks:

arkivstruktur.xml | Linje 1297: Elementet http://www.arkivverket.no/standarder/noark5/arkivstruktur:avskrivningsmaate er ugyldig - Verdien NULL er ugyldig i henhold til datatypen http://www.arkivverket.no/standarder/noark5/metadatakatalog:avskrivningsmaate - Opplistingsbegrensningen mislyktes.

listes opp en haug av ganger i et uttrekk. Kunne vært listet én gang, med henvisning til linjenummere:

arkivstruktur.xml | Elementet http://www.arkivverket.no/standarder/noark5/arkivstruktur:avskrivningsmaate er ugyldig - Verdien NULL er ugyldig i henhold til datatypen http://www.arkivverket.no/standarder/noark5/metadatakatalog:avskrivningsmaate - Opplistingsbegrensningen mislyktes.
Gjelder linje(ne) 1297, 1331, 1432, 1652

etc..

Alternativt henvise til arkade-log.xml for å se alle forekomster av feilen. (bortsett fra at denne per i dag ikke innholder alle..)

**Comment by palm72** [comment]
Støtter veldig å få en konfigurasjonsmulighet. Har testet uttrekk med 120 arkivdeler, og får ikke en gang opp arkivdelens status for alle arkivdeler.

**Comment by stevethearkiv** [comment]
Hvordan fjerner jeg Meg fra denne lista?

Stephen Anthony Jackson
Seniorrådgiver
Arkivverket
Innovasjon, arkiv- og IT-utvikling
Mobil: +47 46 85 00 52
www.arkivverket.no


On 5 Feb 2020, at 15:56, Pål Mjørlund <notifications@github.com> wrote:

﻿

Støtter veldig å få en konfigurasjonsmulighet. Har testet uttrekk med 120 arkivdeler, og får ikke en gang opp arkivdelens status for alle arkivdeler.

**Comment by erikaaberg** [comment]
Forbedret.
