### ISSUE TITLE
Noark-5 testing -> Saksmappens status i arkivstrukturen

### ISSUE THREAD

**Issue by palm72** [arkivverket/arkade5#12]
Testrapporten gir tilbakemelding om at jeg har 1 mappe med status "Utgår" og 33 med status "Avsluttet".
Dette er helt feil. Uttrekket består av 3715 saksmapper hvorav 45 utgår og 3670 har status "Avsluttet". 

Dette ble kontrollert med xPath-spørringer:
`//mappe[@xsi:type='saksmappe']/saksstatus[. = 'Avsluttet']
//mappe[@xsi:type='saksmappe']/saksstatus[. = 'Utgår']`

**Comment by erikaaberg** [comment]
Løst i versjon 7.22
