### ISSUE TITLE
Test N5.39 - antall korrespondanseparter 

### ISSUE THREAD

**Issue by palm72** [arkivverket/arkade5#120]
I versjon 1.5.1.0 av Arkade5 ser det ut til at denne testen teller antall registreringer som har tilknyttet korrespondansepart - og ikke antall korrespondanseparter. 

Det vil si at det blir en underrapportering på antall korrespondanseparter i uttrekket og siden det er registrert korrespondansepart på samtlige registreringer i uttrekkene jeg testet, får jeg opp samme svar i test N5.39 og N5.16

**Comment by joergen-vs** [comment]
Problemet er løst, samtlige korrespondanseparter telles opp nå, uavhengig av forelder-element. Dette blir med i neste versjon.
