### ISSUE TITLE
Versjonsnr i arkade nederst til venstre er feil. Den viser versjon 0.0.0.0

### ISSUE THREAD

**Issue by AnnKnu** [arkivverket/arkade5#121]
![image](https://user-images.githubusercontent.com/43807357/75875405-f1a91100-5e13-11ea-9133-e44a5b948a24.png)

**Comment by joergen-vs** [comment]
Er denne lastet ned fra utgivelsene her, eller dette en versjon du selv har lagd basert på kildekoden?
