### ISSUE TITLE
Occurrences vs. occurences

### ISSUE THREAD

**Issue by PSvendsen** [arkivverket/arkade5#123]
Arkade 5 versjon 1.6.1.0

I ADDML benyttes occurrences i de faste elementene og i Noark 5-bruken av standarden. Occurences er brukt i beskrivelsedokumentet for tilleggselementer og egenskaper.

I kildekoden for Arkade 5 er både occurrences og occurences brukt.

Korrekt skrivemåte er occurrences.

Hva får dette å si for bruken av Arkade 5?
I hvilke situasjoner vil avvikende bruk uavhengig av hva som er riktig skrivemåte, medføre stans i utføring eller manglede utføring av analyser og kontroller?

**Comment by erikaaberg** [comment]
Stygg sak. Vi retter opp i Arkade og anbefalt bruk av ADDML i Norge. Så blir det to r-er overalt. Om det kommer inn noe med 1 r senere vil det bli rettet - og akseptert - i testfasen.

**Comment by erikaaberg** [comment]
Rettet
