### ISSUE TITLE
Fil er ikke en fil

### ISSUE THREAD

**Issue by satch-66** [arkivverket/arkade5#124]
Hei,
Vi forsøker å teste et uttrekk i siste versjon av Arkade (1.6.1.). Filen vi tester, er et uttrekk som er produsert med Arkade5, samme versjon. 

Når vi forsøker å lese den inn, feiler den med meldingen 

`Feil ved innlesing av arkiv: FileStream ble bedt om å åpne en enhet som ikke var en fil. Hvis du trenger støtte for enheter som com1: eller lpt1:, kaller du CreateFile. Deretter bruker du FileStream-konstruktører som tar en OS-referanse som en IntPtr.`

Vi har også gjort samme øvelse med Arkade, versjon 1.3.1.0. Der åpnes uttrekket, og verifiseres uten problemer. Noen som har en anelse om hva som svikter?

**Comment by erikaaberg** [comment]
Denne var veldig snål. Kan det være en melding fra operativsystemet - som ikke har noe med Arkade å gjøre? Vi skulle gjerne hatt mer informasjon: Type arkiv, størrelse på pakke, antall dokumenter, Windows versjon - - Og gjerne noen logger fra Arkade hvis de fortsatt finnes.

**Comment by satch-66** [comment]
Arkivet vi jobber med, er et uttrekk fra Public360 (Version 4.1 SP9 UPD3) på 47,5 GB. Det er produsert av Tieto vha Arkade 5 (versjon 1.6.1.0). Det inneholder 70 000 dokumenter. Vi benytter samme Arkadeversjon, på en maskin som benytter Windows 10 Pro (versjon 1909). Vedlagt er Arkade-loggen, samt skjermbilde med feilmelding.

Håper det hjelper :)
![Skjermbilde](https://user-images.githubusercontent.com/55433908/84230916-52b84300-aaed-11ea-9b29-4cbd07bd97e0.PNG)
[arkade-20200610.log](https://github.com/arkivverket/arkade5/files/4756368/arkade-20200610.log)

**Comment by erikaaberg** [comment]
Hei igjen. Vanskelig det her. Ut fra det vi kan se av programkoden kan vi ikke skjønne annet enn at dette må være en feil som kommer lenger "nedenfra" - det vil si fra filsystemet eller operativsystemet.  Enten kunne ikke Arkade opprette filen, eller så er den ikke mulig å endre fila. Det kan være noe med aksess rettigheter som har endret seg, noe som har "forsvunnet" i filsystemet, eller inkonsekvens i filsystemet. Men vi vil prøve å bedre feilmeldingene i Arkade når tilsvarende situasjoner oppstår.

**Comment by erikaaberg** [comment]
Arkade prøver å formidle feil fra OS-et på en leselig måte, og har forbedret rutinene. Denne issue må vi vel da lukke.
