### ISSUE TITLE
Arkade 5 2.1 fungerer ikke på Windows-server

### ISSUE THREAD

**Issue by larsbrodal** [arkivverket/arkade5#125]
Arkade 2.1 fungerer ikke på Windows server 2016 eller 2019. Det har fungert med eldre versjoner av Arkade. Får konsekvent feilmelding "Feil ved innlesing av arkiv: Object reference not set to an instance of an object" ved innlasting av arkiv. Testet samme uttrekk på vanlig Windows 10-maskin med samme versjon av Arkade. Det fungerer. Testet med flere ulike uttrekk på flere servere.

**Comment by joergen-vs** [comment]
Dette kan være flere årsaker til, har du mulighet til å sende logg-filen som Arkade produserer til arkade5@arkivverket.no? Den gir et bedre bilde av hvor i koden feilen oppstår, siden feilen involverer hele strukturen til arkivuttrekket.

**Comment by joergen-vs** [comment]
Arkade kommer til
```
            var rootDirectory = new DirectoryInfo(
                Path.Combine(ArkadeProcessingArea.WorkDirectory.FullName, dateString + "-" + uuid.GetValue())
            );
```
Har du satt et prosesseringsområde i innstillinger?
![image](https://user-images.githubusercontent.com/10667652/91777016-04e44000-ebef-11ea-90f2-77b9d4e7a22f.png)

**Comment by larsbrodal** [comment]
Ser ut til at ny temp-dir løste problemet.
