### ISSUE TITLE
Sjekk koordinatsystemverdi

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/arkade5#127]
I neste versjon av Noark 5 kommer det nasjonale identifikatorer, deriblant geografisk posisjon med koordinatsystem.  Verdien for koordinatsystem bør sjekkes for å sikre at det er gyldig verdi.

Se https://github.com/arkivverket/noark5-standard/pull/94 for endel pekere

**Comment by erikaaberg** [comment]
Dette kan vi dessverre ikke prioritere.

**Comment by petterreinholdtsen** [comment]
En enkel sjekk vil være å undersøke om formatet er «EPSG:{nummer}», der {nummer} er en tallkode, og gi et varsel hvis et annet strengformat er brukt, da alle ikke-EPSG-verdier skal koordineres med Arkivverket.
