### ISSUE TITLE
Arkade 5 oppretter mapper uten å si fra

### ISSUE THREAD

**Issue by Viken-Petter** [arkivverket/arkade5#128]
Arkade 2.5.0

Kom over denne feature'n da jeg brukte Arkade 5 (GUI) til å teste uttrekk på to forskjellige eksterne disker.
Arkade 5 oppretter katalogstrukturen til prosesseringsområdet hvis det ikke finnes fra før, neste gang Arkade 5 startes.
I mitt tilfelle var det uventet og uønsket funksjonalitet.

Gjenskapes slik:
1. Opprett en katalog eller katalogstruktur for der du ønsker at resultatet fra Arkade 5-kjøringen skal havne (prosesseringsområdet)
2. Start Arkade 5 og oppgi aktuell katalog som prosesseringsområde
3. Avslutt Arkade 5
4. Fjern katalogen eller katalogstrukturen, eller bytt fra én ekstern disk til en annen i samme USB-port. Disken som det evt. byttes til, skal ikke ha katalogen eller katalogstrukturen fra før.
5. Start Arkade 5
6. Katalogen eller katalogstrukturen i punkt 1 er opprettet på nytt, enten på samme disk eller på den evt. andre eksterne disken

**Comment by joergen-vs** [comment]
Problemet er identifisert og videresendt til utviklerne.

**Comment by erikaaberg** [comment]
Feil fixet.
