### ISSUE TITLE
Bruk av headerLevel ved nøkkelkontroll

### ISSUE THREAD

**Issue by Viken-Petter** [arkivverket/arkade5#129]
Arkade 2.5.0

Jeg lurer på om Arkade 5 benytter ADDML 8.3-elementet headerLevel, spesielt ved fremmednøkkelkontroll.
Noen resultater kan tyde på at det ikke blir tatt hensyn til headerposten ved slike kontroller.
Også flott med info hvor og evt. hvor ikke headerLevel spiller noen rolle.

**Comment by Viken-Petter** [comment]
Er det planen at Arkade 5 skal bygge på ADDML 8.3 eller vil applikasjonen fortsatt følge ADDML 8.2 med de begrensningene det har på behandlingen av uttrekk med tegnseparerte datafiler med header?

**Comment by Viken-Petter** [comment]
Med versjon 2.6.0 er vel dette løst?

**Comment by erikaaberg** [comment]
Løst i versjon 2.6.0 - ref. Jira 144 og 456, ref. siste kommentar fra Viken-Petter.
