### ISSUE TITLE
Noark-5 testing: Antall mapper som er klassifisert med hver enkelt klasse i arkivstrukturen

### ISSUE THREAD

**Issue by palm72** [arkivverket/arkade5#13]
Utført i Arkade5 versjon 0.5.7.0:

Testrapporten viser kun 1 av 507 klasser i uttrekket som inneholder mapper. 
Det ser ut til at det er siste benyttede klasse i uttrekket som vises.

**Comment by erikaaberg** [comment]
Løst i versjon 7.22
