### ISSUE TITLE
Endret AH.03 - Kontroll av ugyldig postskille eller feil antall felter i CSV-filer

### ISSUE THREAD

**Issue by Viken-Petter** [arkivverket/arkade5#132]
Arkade 5 versjon 2.5.1
I et datasett med CSV-filer hvor tekstfelt er omsluttet av anførselstegn, forekommer det i noen feltverdier anførselstegn. I disse tilfellene er anførselstegnet escaped med et anførselstegn slik som beskrevet i RFC 4180 punkt 2.7.
https://datatracker.ietf.org/doc/html/rfc4180

I versjon 2.3.2 av Arkade 5 blir ikke dette rapportert, mens det i versjon 2.5.1 kommer følgende melding:
OTAKTIVITETTEKST/AKTIVITETTEKST/	Uventet felt-antall (funnet/forventet): 11/10 Felttekst: "AADPAAAADVSN";"GENERELT";1;"";"Akershu

Jeg vet ikke i hvilken versjon av Arkade 5 dette ble endret.

Er det meningen at Arkade 5 skal følge RFC 4180 på dette punktet?

**Comment by erikaaberg** [comment]
Delvis løst. Arbeides fortsatt med. Ref. Jira 659.

**Comment by erikaaberg** [comment]
Rettet i versjon 2.9.0.
