### ISSUE TITLE
Test av datofelt i CSV-filer rapporterer at gyldige verdier er feil

### ISSUE THREAD

**Issue by Viken-Petter** [arkivverket/arkade5#133]
Arkade 5 versjon 2.5.1

I testrapporten listes alle datofeltverdier opp som feil for datofelt med prosessen Control_DataFormat.
Dette gjelder i dette tilfellet datoer i formatene DD.MM.YYYY og YYYY-MM-DD.
Resultatet er det samme både med og uten datoer omsluttet av anførselstegn.

Vedlagte addml.xml har fått filendelsen txt lagt til for å bli godtatt av GitHub. 
[addml.xml.txt](https://github.com/arkivverket/arkade5/files/7949811/addml.xml.txt)
[vaksiner.csv](https://github.com/arkivverket/arkade5/files/7949813/vaksiner.csv)
[arkade-testrapport_1b012405-8700-4db3-bb79-ebbe7aadf830.pdf](https://github.com/arkivverket/arkade5/files/7949818/arkade-testrapport_1b012405-8700-4db3-bb79-ebbe7aadf830.pdf)

**Comment by joergen-vs** [comment]
Handler om [standard dato- og tidsformat på tekststreng](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings), "D" er "lang dag"-format mens  "Y" og "y" brukes forskjellig (uten å kunne gi bedre grunn) for år. Riktig bruk for feltene hos deg er følgende;
DD.MM.YYYY -> dd.MM.yyyy
YYYY-MM-DD -> yyyy-MM-dd
