### ISSUE TITLE
A.12 - Kontroll av antall poster - behov for egenskapsavklaring

### ISSUE THREAD

**Issue by Viken-Petter** [arkivverket/arkade5#134]
Arkade 5 versjon 2.5.1

A.12 - Kontroll av antall poster (utført på CSV-filer)
Prosessangivelse: Control_NumberOfRecords (på filnivå)

I "ADDML 8.3 Arkivverkets profil" 
( https://www.arkivverket.no/forvaltning-og-utvikling/regelverk-og-standarder/andre-arkivstandarder/addml-archival-data-description-markup-language/_/attachment/download/94c6a79e-d1af-40ae-b1ef-3e754f762d95:f0fadebbc99ef785cca2c674726846f2c5603ae5/ADDML%208-3%20Profil%20Arkivverket.pdf ) 
står det i utgaven datert 10.06.2020 følgende:

"Control_NumberOfRecords
Teller opp og kontrollerer at antall poster i filen er lik antallet som er oppgitt i 
egenskapen numberOfOccurrences i flatFile."

Selv om Arkade 5 er bygget på ADDML 8.2, gjelder det som står i ADDML 8.3-dokumentet om numberOfOccurrences også for ADDML 8.2.

Arkade 5 kommer med følgende feilmelding når numberOfOccurrences er oppgitt i flatFile:

"Expected number of records not specified. Unable to control number of records."

I headingen til prosessen i Arkades testrapport står det:
"Teller opp og kontrollerer at antall poster i filen er lik antallet som er oppgitt i egenskapen numberOfRecords i flatFile"

Når jeg bytter ut navnet på egenskapen med antall poster fra numberOfOccurrences til numberOfRecords i ADDML-filen, fungerer prosessen etter hensikten.

Betyr dette at Arkade 5 ikke forholder seg til beskrivelsen/definisjonen av ADDML 8.2/8.3 på dette punktet med overlegg eller skulle prosessen ha forholdt seg til numberOfOccurrences-egenskapen?

**Comment by erikaaberg** [comment]
Problem løst. i versjon 2.6.0. Ref. Jira 548.
