### ISSUE TITLE
Validation of file/file and file/record relations

### ISSUE THREAD

**Issue by douzounov** [arkivverket/arkade5#135]
Below are a few questions related to Arkade and how it validates Noark 5.5 packages. Note that the questions are also applicable to earlier versions of Noark supported by Arkade.

According to arkivstruktur.xsd, any file type (mappe, saksmappe, moetemappe) can be linked to any type of record (registrering, journalpost, arkivnotat, moeteregistrering). However, the text of the standard imposes some restrictions (the ones below are just examples, not a complete list):
* It seems that meeting records (moeteregistrering) can only have a meeting folder (moetemappe) parent: "En tredje type spesialisering er møteregistrering, som skal knyttes til en møtemappe."
* The standard does not explicitly state that a registry entry (journalpost) can only be linked only to a case file (saksmappe), but certain requirements on registry entry (journalpost) fields imply that. For example, for journalpostnummer, the metadata catalog states that "Viser rekkefølgen på journalpostene innenfor saksmappen".

Furthermore, according to arkivstruktur.xsd, any type of file (mappe, saksmappe, moetemappe) can have any type of file (mappe, saksmappe, moetemappe) as a child. However, the text of the standard implicitly restricts some of the theoretically possible relations.

I would like to confirm the following:
* Is it allowed for any file type (mappe, saksmappe, moetemappe) to be linked to any record type (registrering, journalpost, arkivnotat, moeteregistrering)?
    * If yes, can you please point me to the text in the standard that confirms this?
    * If no, what are the only allowed relations between file and record types and can Arkade check for these when validating extraction packages?
* Is it allowed for any file type (mappe, saksmappe, moetemappe) to have any other type of file (mappe, saksmappe, moetemappe) as parent?
    * If yes, can you please point me to the text in the standard that confirms this?
    * If not, what are the allowed relations and can Arkade check for these when validating packages?

**Comment by joergen-vs** [comment]
- No, direct link between any file and any record is not allowed. However, depending on how the system is configured, you may find a file containing a case file, containing a registry entry.

  - "journalpost" / "registry entry", or "documents subject to record keeping", must be linked to "saksmappe" / "case file" [req. 2.5.2]

  - "moeteregistrering" / "meeting record" should be linked to "moetemappe" / "meeting file" [req. 2.5.3]
  - "registrering" / "record" may be linked to all files

Other file and record types may be introduced, based on the base types, such as "building file" and -record. Relevant requirements to file and record is 2.5.1-2.5.5 and 2.6.1-2, 2.6..4-6

Arkade 5 will list the record types in an analysis, and **it's up to the tester to recognise this for further investigation**.
<br>
- Yes, it's allowed. The link file to subfile has no further requirements. Documentation is available in the datamodel-chapter, same as the previous answer. [Permalink](https://github.com/arkivverket/noark5-standard/blob/dd919106eea85c0de71c8d4284416f2a693374ff/kapitler/030-noark-5-datamodell.rst). 

Here is a quote from Noark 5 v2.0, regarding subfiles.
> It must be possible to create a file hierarchy of subfiles (specified as a self-relation in the Basic file). In most cases, one level of subfiles will be sufficient, but Noark 5 also opens up the possibility of several levels of such files. This will first and foremost be relevant for task systems. The content of subfiles will normally be grouped according to content, not according to activities. Many task systems group documents according to type, e.g. invoices, orders, correspondence, etc. In a file with meeting documents, they could for example be grouped according to delegated cases, referred cases, interpellations, etc.

**Comment by erikaaberg** [comment]
Bortfaller. Ref dialog over.
