### ISSUE TITLE
Malware funnet i arkade5-2.5.0.msi | Malware found in arkade5-2.5.0.msi

### ISSUE THREAD

**Issue by Swoy** [arkivverket/arkade5#136]
Det er mulig det er et signaturproblem, men jeg velger å rapportere det uansett. Både McAfee (Artemis Virustotal) og MalwareBytes rapporterer mistenkelig aktivitet i den siste msi-en fra arkade5 med sjekksum:
6DB477C26A442BD619C4F13DF5E8759A1766EEF5AFC4DACAE7FBEEA5F8C665FD

Siden det er msi ment for deployment så vil jeg anta at dere ønsker å ta en titt.

---
It is possible this is related to a signature problem, but I choose to report it anyway. Both McAfee (through Artemis in VirusTotal) and Malwarebytes report suspicious activity in the last release of arkade5, with checksum: 6DB477C26A442BD619C4F13DF5E8759A1766EEF5AFC4DACAE7FBEEA5F8C665FD

Because this is a msi-file meant for deployment, I assume you would want to look into it.

**Comment by erikaaberg** [comment]
Dette tror vi nå er løst. Gjeldende fra versjon 2.7
