### ISSUE TITLE
Flate filer - Det er ikke riktig at tom verdi i felt med koder alltid er feil

### ISSUE THREAD

**Issue by Viken-Petter** [arkivverket/arkade5#137]
Arkade 5 versjon 2.6.0

Vedlagte arkivuttrekk (CSV) inneholder felt med koder som er definert i addml.xml.
Feltet "Neste aktivitet" er ikke obligatorisk, mens feltet "Registrert av" er obligatorisk (notNull).
Slik jeg tolker intensjonen med beskrivelsen sett opp mot datafilen, er at det skal være tillatt med tomme verdier i "Neste aktivitet", men ikke i "Registrert av".

Selv om det er definert kodeverdier for et felt, betyr ikke det at det må forekomme en verdi uavhengig av om feltet er definert som obligatorisk eller ikke.

Prosessen Control_Codes rapporterer alltid om feil ("Ikke i kodelisten") for tomme verdier. 

addml.xml har fått endelsen txt for å bli svelget av GitHub
[datafil.csv](https://github.com/arkivverket/arkade5/files/8450556/datafil.csv)
[addml.xml.txt](https://github.com/arkivverket/arkade5/files/8450557/addml.xml.txt)
.

**Comment by Viken-Petter** [comment]
[arkade-testrapport_d3b024ff-6bec-40d1-802c-8cf966a67b11.pdf](https://github.com/arkivverket/arkade5/files/8450628/arkade-testrapport_d3b024ff-6bec-40d1-802c-8cf966a67b11.pdf)

**Comment by erikaaberg** [comment]
Rettet i versjon 2.7.0
