### ISSUE TITLE
Noark 5 - Hvilken fil er det som ikke finnes?

### ISSUE THREAD

**Issue by Viken-Petter** [arkivverket/arkade5#139]
Arkade 5 (versjon 2.6.0)

Fra testrapporten (Noark 5):

"N5.30 - Dokumentfilers sjekksummer
Type: Innholdskontroll

Resultater
Lokasjon	Melding
arkivuttrekk.xml - linje(r): 0	Filen ble ikke funnet"

Det hadde vært veldig nyttig å få med filnavnet til den eller de filene (arkivdokumentene) som mangler i arkivuttrekket.
Nødvendig informasjon ligger jo i arkivstruktur.xml.

**Comment by erikaaberg** [comment]
Arbeides med. Ref. Jira 648.

**Comment by erikaaberg** [comment]
Ikke reproduserbar. Lukkes.
