### ISSUE TITLE
Noark-5 rapportering: Antall mapper uten registreringer eller undermapper

### ISSUE THREAD

**Issue by palm72** [arkivverket/arkade5#14]
Testen bør rapportere mappeID, mappetittel og evt. saksstatus for å vise om det skyldes feilregistreringer eller om en reelt bør forvente innhold i mappen.

**Comment by palm72** [comment]
Tilsvarende bør registreringsID vises når en journalpost mangler hoveddokument. Det rapporteres i dag systemID for journalpost mens arkivskaper trenger saks- og dokumentnummer for å kontrollere i produksjonssystemet.

**Comment by joafug** [comment]
Status:
Det er satt i gang et arbeid for forbedre rapportene, eventuelt dele opp i forenklet og avansert rapport.

Dette er dessverre et større arbeid og komer til å ta noe tid.

**Comment by AnnKnu** [comment]
Hva er status på denne @erikaaberg og Jørgen?

**Comment by erikaaberg** [comment]
Den sitter litt lenger inne - - vi arbeider med saken - - men den kommer ikke med i den release som er denne uka.

**Comment by erikaaberg** [comment]
Løst i versjon 2.9.0.
