### ISSUE TITLE
Fagsystem/CSV - Manglende verdi i integer-felt blir rapportert feil (ugyldig dataformat, fanger ikke opp NotNull)

### ISSUE THREAD

**Issue by Viken-Petter** [arkivverket/arkade5#141]
Arkade 5 versjon 2.7.0

Utgangspunktet er en CSV-fil med fire felt.
Felt1 - string - obligatorisk
Felt2 - integer - Ikke obligatorisk
Felt3 - integer - Obligatorisk
Felt4 - string - ikke obligatorisk

Det er definert " som omslutningstegn, og verdier i de to string-feltene har omslutningstegn, mens integer-feltene ikke har det.

Innholdet i CSV-filen:

"Felt1";"Felt2";"Felt3";"Felt4"
"AAA";4;5;"BBB"
"AAA";;5;"BBB"
"AAA";4;;"BBB"
"AAA";;;"BBB"
;4;5;

Det er lagt på DataFormat-kontroll på alle feltene, og på de to obligatoriske feltene er det lagt på NotNull-kontroll.

Under er relevante deler av resultatet fra Arkade 5-kjøringen:

![Fra_rapport](https://user-images.githubusercontent.com/86402326/186873363-673e6843-7a5a-44b4-a039-6b4a917b08bc.PNG)

1. Som en ser, rapporterer Arkade 5 at felt med manglende integer-verdier har feil i dataformatet. En manglende verdi har ikke feil dataformat.

2. Arkade 5 rapporterer også om at ingen feil er funnet når det gjelder manglende obligatoriske verdier. Det mangler obligatorisk verdi for Felt3 i linje 4 og 5 (post 3 og 4).

3. Det mangler en 'n' i A.20: "Kontrollerer om det fines null-verdier i feltet.
[En_fil.csv](https://github.com/arkivverket/arkade5/files/9431946/En_fil.csv)
[addml.xml.txt](https://github.com/arkivverket/arkade5/files/9431947/addml.xml.txt)
"

**Comment by erikaaberg** [comment]
Lagt inn som task i vår Jira.

**Comment by Viken-Petter** [comment]
Arkade 5 versjon 2.8.0

Det ser ut til at Arkade 5 klarer å forholde seg til tomme felt med kun omslutningstegn (anførselstegn) nå.

Men Control_NotNull fanger ikke opp tomme felt (generelt?). Vedlagte eksempel er fra en CSV-fil uten omslutningstegn. 
 
[arkade-20230109.log](https://github.com/arkivverket/arkade5/files/10372869/arkade-20230109.log)
[Fil_1.csv](https://github.com/arkivverket/arkade5/files/10372870/Fil_1.csv)
[addml.xml.txt](https://github.com/arkivverket/arkade5/files/10372871/addml.xml.txt)

**Comment by erikaaberg** [comment]
Dette er fixet. Kommer med i neste versjon (2.9.0).
