### ISSUE TITLE
Memory errror veraPDF mappe i Arkade 5 v2.7.0

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#142]
Arkade 5 v2.7.0 arkivversjon validering med veraPDF feiler pga. for lite minne.

Hvordan settes Arkade opp for å øke minne brukt av Java kallt opp fra Arkade?

Eksempelet har 128 GB størrelse på \dokumenter og største dokument er på 710 MB (PDF scannet byggesaktegning).

2022-08-25T19:08:24.630 [Error] Arkivverket.Arkade.Core.Util.ArchiveFormatValidation.PdfAValidator Validation failed: Exception of type 'System.OutOfMemoryException' was thrown.

![Arkade5_v2 7 0_verapdf-error-1](https://user-images.githubusercontent.com/622856/186885158-8f023c15-fd12-4815-83e4-2253e81531a4.png)
![Arkade5_v2 7 0_verapdf-error-2](https://user-images.githubusercontent.com/622856/186885166-95118c0c-1fc4-497a-900c-0626acc535c3.png)
[arkade-20220825.log](https://github.com/arkivverket/arkade5/files/9432380/arkade-20220825.log)

**Comment by erikaaberg** [comment]
Mulig dette ikke er så enkelt - - mye av dette ligger innenfor veraPDF software. 

Men vi tar en liten titt og ser om det er mulig å gjøre et hack. Kommer tilbake til skaen..
