### ISSUE TITLE
Fagsystem/CSV - Feiler på tomme string-felt med anførselstegn

### ISSUE THREAD

**Issue by Viken-Petter** [arkivverket/arkade5#143]
Arkade 5 versjon 2.7.0

Utgangspunktet er samme datafil som i issue #141, men med en post lagt til nest sist i datafilen. Ingen angitte prosesser.

"Felt1";"Felt2";"Felt3";"Felt4"
"AAA";4;5;"BBB"
"AAA";;5;"BBB"
"AAA";4;;"BBB"
"AAA";;;"BBB"
"";4;5;""
;4;5;

Innlesingen feiler på den nye posten:
"";4;5;""

Se feilmelding fra Arkade 5:

![arkade5_gui_med_feil](https://user-images.githubusercontent.com/86402326/186897504-0a8a06da-b4a3-44ae-8b21-01818def962f.PNG)
[En_fil.csv](https://github.com/arkivverket/arkade5/files/9432865/En_fil.csv)
[addml.xml.txt](https://github.com/arkivverket/arkade5/files/9432866/addml.xml.txt)

**Comment by erikaaberg** [comment]
Lagt inn som task i vår Jira (samme task som #141).

**Comment by Viken-Petter** [comment]
Arkade 5 versjon 2.8.0

Det ser ut til at Arkade 5 klarer å forholde seg til tomme felt med kun omslutningstegn (anførselstegn) nå.
Er det mulig å få det bekreftet, eller avkreftet?

**Comment by erikaaberg** [comment]
Bekreftes herved.

**Comment by erikaaberg** [comment]
Fungerer fra og med 2.8.0
