### ISSUE TITLE
Arkade 5 v2.7.0 PRONOM forbedre fil ".._filformatinfo-statistikk.csv"

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#144]
Det er ønskelig at _filformatinfo-statistikk.csv kan autoprosesseres av produksjonslinjen som bruker Arkade 5 (f. eks. i konsollversjonen som en del av et større produksjonsmiljø). For å kunne gjøre dette må data i statistikk-fila være konsistent med dedikerte felt-separatorer som finnes i samme posisjon alltid for alle filtyper i lista.

Arkade 5 v2.7.0:
 A. filformatinfo.csv.: Ser ut til å ha nøyktig samme innhold som i v2.5.0 og er bra
 B. filformatinfo-statistikk.csv manger elementer og er uegnet for dataprosessering

Endringsønske til filformatinfo-statistikk.csv
 1. Inkludere MIME type/navn som kolonne
 2. Formattere slik at filen kan dataprosesseres (konsistente tegnseparatorer)
 3. Inkludere versjon av Siegfried (lagre som egen loggfil ved siden av de 2 eksisterende filer?)
 4. Inkludere versjon av PRONOM Signatur og PRONOM Container som ble brukt (lagre som egen loggfil ved siden av de 2 eksisterende filer?)

Om punkt 2.
 a) Kan det bekreftes at komma "," kun vil kunne være der EN gang pr. rad, dvs at komma er der alltid til slutt etterfulgt av antall filer forekomster som tall bak komma? Det skal finnes komma i de andre feltene for noen filtyper (Format name eller Format version eller MIME type/navn)? Vasker Arkade 5 teksten da for å erstatte komma?

 b) Er bruken av bindestrek også konsistent slik at disse KUN finnes som feltseparator pr. rad altså mellom kolonnene PUID, Format name, Format version og ev. MIME type/navn hvis den kolonnen legges til)?

_filformatinfo-statistikk.csv har en rad pr. filtyoe med kolonner:
 - PUID (no sortert alfabetisk pr. PUID, før usortert)
 - Format Name
 - Format Version
 - Antall forekomster

_filformatinfo.csv har en rad pr. fil med kolonner:
 - Komplett filsti (path + filename)
 - Filendelse (f.eks.: ".pdf")
 - PUID
 - Format Name
 - Format Version
 - MIME type/navn
 - Feil

[DROID signature & container files (archive)](https://www.nationalarchives.gov.uk/aboutapps/pronom/droid-signature-files.htm)
DROID_SignatureFile_V108.xml pr. dato siste signaturer
container-signature-20220905.xml pr. dato siste container

**Comment by solfeggietto** [comment]
filformatinfo.xml har likevel en mangel og et forbedringspotensiale
 - Filstørrelse bør være med som en felt-kolonne, for i filanalyse av dokumentene er dette en avgjørende parameter!
 - Pakkede filer (zip, 7zip, rar, tar m.m.) vises no bare som en fil, og her kan Arkade 5 vurdere å lage en egen liste over disse filenes innholdselementer (altså PRONOM analyse av filene inne i de pakkede filene slik DROID gjør det og sikkert SIEGFRIED har mulighet til å gjøre det)

Når Arkade 5 først parser gjennom alle filer for å analysere PRONOM filformat, så kan følgende statistikk også akkumuleres:
 - Minste filstørrelse
 - Største filstørrelse
 - Gjennomsnittlig filstørrelse
 - Kanskje en vekting av hvor mange filstørrelser i ulike segment
 - F. eks.: < 100 kb | 100 kb - 1 MB | 1 MB - 20 MB | 20 MB - 100 MB | > 100 MB
 - Eller om andre oppdelinger her er fornuftige

**Comment by solfeggietto** [comment]
Eksempel fra en XPath kjørt mot arkivstruktur.xml metadata på et Noark 5-uttrekk vist under.
Tilsvarende kan man gjøre i analysen av selve dokumentfilene (altså data).

N5.26.03 Dokumentstørrelser
, 1 x =0
, 5 x =1-9
, 26 x =10-99
, 42 x =100-199
, 319 x =200-499
, 2512 x =500-999
, 503 x =1000-1999
, 25017 x =2000-9999
, 233518 x =10k-100k
, 524865 x =100k-1M
, 92872 x =1M-10M
, 8439 x =10M-100M
, 559 x >= 100M
 
, Snitt: 805,529
, Max: 987,451,655
, Sum: 715,856,249,285

**Comment by erikaaberg** [comment]
Jeg kommenterer innimellom i _kursiv_. Generelt: Utvalgte legges inn som prioritering i vår Jira.

------------------ Innlegg 1 -----------------------------------
Det er ønskelig at _filformatinfo-statistikk.csv kan autoprosesseres av produksjonslinjen som bruker Arkade 5 (f. eks. i konsollversjonen som en del av et større produksjonsmiljø). For å kunne gjøre dette må data i statistikk-fila være konsistent med dedikerte felt-separatorer som finnes i samme posisjon alltid for alle filtyper i lista.

Arkade 5 v2.7.0:
A. filformatinfo.csv.: Ser ut til å ha nøyktig samme innhold som i v2.5.0 og er bra
B. filformatinfo-statistikk.csv manger elementer og er uegnet for dataprosessering    - _Enig_

Endringsønske til filformatinfo-statistikk.csv

Inkludere MIME type/navn som kolonne   _Lurt_
Formattere slik at filen kan dataprosesseres (konsistente tegnseparatorer) 
   _Enig. Det er for så viddt konsistent, men noe infor er "slått sammen"_
Inkludere versjon av Siegfried (lagre som egen loggfil ved siden av de 2 eksisterende filer?) - _Prioriteres ikke_
Inkludere versjon av PRONOM Signatur og PRONOM Container som ble brukt (lagre som egen loggfil ved siden av de 2 eksisterende filer?) _Prioriteres ikke_
Om punkt 2.
a) Kan det bekreftes at komma "," kun vil kunne være der EN gang pr. rad, dvs at komma er der alltid til slutt etterfulgt av antall filer forekomster som tall bak komma? Det skal finnes komma i de andre feltene for noen filtyper (Format name eller Format version eller MIME type/navn)? Vasker Arkade 5 teksten da for å erstatte komma?

_Ja. Det må vi få til_

b) Er bruken av bindestrek også konsistent slik at disse KUN finnes som feltseparator pr. rad altså mellom kolonnene PUID, Format name, Format version og ev. MIME type/navn hvis den kolonnen legges til)?
_Vi vil bruke komma som separator. Bindestrek kan "binde sammen" info til en kolonne, men bør unngås. Enig i det._

_filformatinfo-statistikk.csv har en rad pr. filtyoe med kolonner:

PUID (no sortert alfabetisk pr. PUID, før usortert)
Format Name
Format Version
Antall forekomster
_filformatinfo.csv har en rad pr. fil med kolonner:

_Alle disse vil bli vurdert_

Komplett filsti (path + filename)  _Tror ikke full path blir med._
Filendelse (f.eks.: ".pdf")  - _Ja_
PUID - _Ja_
Format Name - _Ja_
Format Version - _Antagelig - - -_ 
MIME type/navn  - _Ja (når entydig?)_
Feil - _Mener du "ikke funnet"_

------------------ Innlegg 2 -----------------------------------
filformatinfo.xml har likevel en mangel og et forbedringspotensiale

    Filstørrelse bør være med som en felt-kolonne, for i filanalyse av dokumentene er dette en avgjørende parameter!
    Pakkede filer (zip, 7zip, rar, tar m.m.) vises no bare som en fil, og her kan Arkade 5 vurdere å lage en egen liste over disse filenes innholdselementer (altså PRONOM analyse av filene inne i de pakkede filene slik DROID gjør det og sikkert SIEGFRIED har mulighet til å gjøre det)

_Enig - filstørrelse bør med_
_Analyse av filer inne i ZIP-filer kommer med i neste versjon (er allerede utviklet)_

Når Arkade 5 først parser gjennom alle filer for å analysere PRONOM filformat, så kan følgende statistikk også akkumuleres:

    Minste filstørrelse  
    Største filstørrelse 
    Gjennomsnittlig filstørrelse 
    Summert filstørrelse alle filer
    Kanskje en vekting av hvor mange filstørrelser i ulike segment
    F. eks.: < 100 kb | 100 kb - 1 MB | 1 MB - 20 MB | 20 MB - 100 MB | > 100 MB
    Eller om andre oppdelinger her er fornuftige

Tror ikke vi tar med noen av disse. Det kan enkelt gjøres i Excel når filstørrelse kommer med.
-----------------------------------------------------------------------------------------------------------

**Comment by erikaaberg** [comment]
Info i list og statistikk er forbedret.
