### ISSUE TITLE
arkade-log.xml mangler i SIP for Arkade 5 v2.7.0

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#145]
arkade-log.xml mangler i "arkade-resultater_<uuid>" mappen ved generering av SIP for Arkade 5 v2.7.0

For en AIP ligger den eks. her:
Y:\uttrekk-arkade\version\v2.7.0\noark5_aip\tar-09b4fa88-05ca-4733-ab11-b9afd5d81428\administrative_metadata\repository_operations\arkade-log.xml

Altså i mappen over "testrapporter" som for AIP er med i pakken.

**Comment by erikaaberg** [comment]
Vi har sammenliknet arkade.log.xml med (de maskinlesbare variantene av) test-rapporten og vi har vel kommet til  at arkade-log egentlig tilfører så mye at vi vil legge inn dette som standard. (ut fra en kost/nytte verdi)

**Comment by erikaaberg** [comment]
Lukker saken. Ref. kommentar over.
