### ISSUE TITLE
Arkade 5 v2.8.0 statusteller validering av arkivformat

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#146]
Validering av arkivformat pdf/a fungerer no i Arkade 5 v2.8.0 på mapper, slik at f. eks. hele dokumenter mappen i et Noark 5-uttrekk kan valideres for arkivformatet PDF/A.

Imidlertid så vises der ikke statusindikator, slik det vises for PRONOM filanalysen på samme samling av dokumenter (f. eks. hele dokumenter mappen i samme Noark 5-uttrekket). Dette gjør at analyse av stort antall filer blir stående å kjøre lenge uten noen statusindikator, får jobben er ferdig eller det bare blir stående og henge om progammet krasjer/går i loop.

Ønske: vise 125 345 av 1 000 000 for validering av arkivformat, slik det vises for PRONOM filanalysen.

**Comment by erikaaberg** [comment]
Ja. Det bør vi ha. Med forbehold om manglende teknisk kompetanse - det bør være mulig (Ny Arkade sak 675).

**Comment by solfeggietto** [comment]
Her er en jobb med validering pdfa som ble satt på fredag og fortsatt står og jobber (eller hva den gjør, vises jo ikke indikator).
Jeg har et spørsmål til Oppgavebehandling, hva og hvorfor er de 2 "Windows Update Medic-tjeneste" der?

![Arkade5_v2 8 0_2022-11-18_progress-1](https://user-images.githubusercontent.com/622856/202991734-c62dc446-9aca-4ffd-afd8-94f659ec831f.png)
![Arkade5_v2 8 0_2022-11-18_progress-2](https://user-images.githubusercontent.com/622856/202991755-cbf4c705-522c-4e9f-b796-a46e090e6106.png)
![Arkade5_v2 8 0_2022-11-18_progress-3](https://user-images.githubusercontent.com/622856/202991769-f316debc-2035-4f54-a387-201286e27ce6.png)

**Comment by erikaaberg** [comment]
Enig. Hadde vært innmari kjekt å ha. Det krever imidlertid en del omskriving - og vil antagelig gå ut over performance. Kan dessverre ikke prioriteres foreløpig.
