### ISSUE TITLE
Arkade 5 v2.8.0 inkludere PRONOM og validering arkivformat i hovedtest

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#147]
No fungerer hovedtest (f. eks. Noark 5), PRONOM analyse og validering av filformat fint hver for seg. For store uttrekk kan det ta lang tid å kjøre disse testene og det er da lite effektivt å måtte vente på en jobb, for å starte neste som tar like lang tid. Jeg vet det er mulig å automatisere via Arkade 5 CLI kall fra en egen automatisert prosess, men likevel er det ønskelig at man i Arkade 5 GUI kunne inkludere verktøy-tester valgbare fra hovedtesten, slik man allerede i dag kan velge (vekk riktig nok) testene i f. eks. et Noark 5-uttrekk.

Resultater at PRONOM og validering arkivformat kan også inkluderes i SIP og AIP
- administrative_metadata\repository_operations\testrapporter
eller
- administrative_metadata\repository_operations\pronom
- administrative_metadata\repository_operations\validering_arkivformat

Se vedlagt skjermdump av pdf/a validering kjører uten teller (har kjørte noen timer, må bare vente og se når den ev. blir ferdig)  og av pronom filanalyse kjører med teller.

![Arkade5_v2 8 0_validering-pdfa-run_nocount](https://user-images.githubusercontent.com/622856/201909990-401120be-39e7-4751-9a0d-03b7175e3a33.png)
![Arkade5_v2 8 0_pronom-run-counting](https://user-images.githubusercontent.com/622856/201910000-332fb741-02d1-4cb2-b3d5-4cc45cf2b575.png)

**Comment by erikaaberg** [comment]
1: Inkludering av "verktøy" i hovedtest tror jeg ikke vi kan prioritere - ut fra litt kost/nytte verdi. Det er litt fiklete --

2: Pronom analyse i pakker må vi se litt nærmere på. Mulig det bør være en opsjon. (Ref. Arkade-sak 675)

**Comment by erikaaberg** [comment]
1: Det prioriteres ikke.
2: Er løst.
