### ISSUE TITLE
Arkade5 v2.8.0 error handling når mistet kontakt disk

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#148]
Ønske: Legg til error handling når Source disk/mappe/filer med uttrekk som leses eller Target disk/mappe/filer der resultat skal skrives til blir utilgjengelig etter oppstart av kjøring.

Slik det er no i Arkade 5 v2.8.0 fortsetter programmet å kjøre, uten noen informasjon/advarsel om at programmet faktisk sliter med å lese fra Source eller skrive til Target disk/mappe/filer.

**Comment by erikaaberg** [comment]
Notert som Arkad Jira issue 677.

**Comment by jtellnes** [comment]
Man skal i utgangspunktet få en feilmelding i pakkevinduet dersom man mister tilgang til område(-t/-ene) der kildeuttrekket og/eller pakkefila ligger. I hvilken sammenheng har problemet oppstått (innlasting/testing/pakkeopprettelse)?
