### ISSUE TITLE
Noark-5 rapportering: Antall journalposter

### ISSUE THREAD

**Issue by palm72** [arkivverket/arkade5#15]
Testen gir følgende melding: "Det er ikke samsvar mellom dokumentert antall og faktisk antall journalposter"
Deretter rapporteres det antall journalposter i arkivstruktur.xml, loependeJournal.xml og offentligJournal.xml. Det rapporteres ikke hva som er oppgitt av journalposter i arkivuttrekk.xml

Det vises et avvik ved at loependeJournal og offentligJournal inneholder flere journalposter enn arkivstruktur.xml. Dette oppfatter jeg som normalt ved bruk av periodisering med overlapping.
Etterkontroll viser at arkivstruktur.xml og arkivuttrekk.xml angir samme antall journalposter.
arkivstruktur.xml angir også det samme antall journalposter som testen finner i loependeJournal.xml og offentligJournal.xml. 

Jeg oppfatter det derfor slik at faktisk og dokumentert antall journalposter **samsvarer**, men det er ikke med det samme antall journalposter i journalrapportene som i arkivstruktur.xml. Det siste er ikke en feil dersom det ikke er benyttet skarpt skille i begge ender av arkivdelen.

**Comment by erikaaberg** [comment]
Utgår i versjon 1
