### ISSUE TITLE
Arkade 5 v2.8.0 PRONOM teller liten bug

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#151]
Når vi bruker PRONOM filanalyse to eller flere ganger, så resettes ikke teller for filantall ved oppstarten av den nye PRONOM filsjekk.
 - Se vedlagte bilde 1.6 mill av 1.6 mill filer analysert vises umiddelbart når neste kjøring startes
 - Deretter tar de en stund, og så telles det opp fra 1 som normalt

Bugfix: Få resatt telleren ved start ny kjøring (satt variabel = 0), og så vil den telle fra 1 når programmet har tenkt seg om (sjekker sikkert antall filer i hovedmappe med undermappe osv. som jo kan ta en viss tid avhengig av antall og hastighet maskin og disker).

![Arkade5_v2 8 0_pronom-teller-ikke-resatt](https://user-images.githubusercontent.com/622856/208102998-feccdd01-bffe-41e9-969b-e79dc1a12a0b.png)
![Arkade5_v2 8 0_pronom-teller-startet-igjen](https://user-images.githubusercontent.com/622856/208103019-d05350df-839d-497e-b5b9-3ca94bbcc895.png)

**Comment by erikaaberg** [comment]
Fixet i 2.9.0
