### ISSUE TITLE
Flate filer/fagsystem - Control_DataFormat feiler for datoer

### ISSUE THREAD

**Issue by Viken-Petter** [arkivverket/arkade5#153]
Arkade 5 versjon 2.8.0
Ref issue #140

Applikasjonen stopper opp ved ugyldig dato i formatet YYYY-MM-DD (2022-25-01) når Control_DataFormat utføres.

[Fil_1.csv](https://github.com/arkivverket/arkade5/files/10372287/Fil_1.csv)
![a5_v_2_8_0_datokontroll](https://user-images.githubusercontent.com/86402326/211287003-f8999c3c-5b69-4120-8c93-4a2978bf535f.PNG)
[arkade-error-20230109104649.log](https://github.com/arkivverket/arkade5/files/10372290/arkade-error-20230109104649.log)
[addml.xml.txt](https://github.com/arkivverket/arkade5/files/10372297/addml.xml.txt)

**Comment by erikaaberg** [comment]
Fixet i 2.9.0
