### ISSUE TITLE
Arkade 5 v2.8.0 arkade-log.xml mangler i SIP testrapporter

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#155]
Arkade 5 v2.8.0 kan lage SIP og AIP pakker

AIP lagrer testrapporter i .tar fil inklusiv arkade-log.xml
 - <uuid>.tar\administrative_metadata\repository_operations\arkade-log.xml
 -  \administrative_metadata\repository_operations\testrapporter\.. med rapportene

SIP lagrer ikke noe testrapporter i .tar fila
 - <uuid>.tar\administrative_metadata\   ikke noe undermappe ..\repository_operations
 - ekstern mappe \arkade-testrapporter_<uuid>\.. med rapportene
 - MEN arkade-log.xml lagres da ikke => Foreslår at man med valg SIP lagrer arkade-log.xml også eksternt i mappen!

**Comment by erikaaberg** [comment]
Litt dårlig nytt her er jeg redd. Inntil videre endrer vi ikke pakke/mappe/fil-strukturer.
Det blir eventuelt dersom vi åpner for større fleksibilitet som del av en større pakke (sic!).

**Comment by erikaaberg** [comment]
Ref. over. Arkade log xml er erstattet av maskinlesbar testrapport. Vi lukker denne.
