### ISSUE TITLE
Verktøy PRONOM filformat-analyse har ikke progress-bar uegnet for mange GB

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#157]
Arkade 5 v2.80 > Verktøy > PRONOM filformat-analyse
1.  Mappe på 380 GB med 266 mapper og 49 973 filer
2.  Startet PRONOM filformat-analyse (valgt mappen over og en målmappe med .csv fil resultat)
3. Arkade 5 v2.8.0 Verktøy står uten indikator om den henger eller program kjører
4. Oppgavebehandling viser fast minnebruk 81 MB og 0% prosessor

Det minste vi forventer er at programmet sier hva som skjer
- Leser kildemappe? (kanskje man parser gjennom alle undermapper og filer først)?
- Er det mulig å definere noen mellomsteg som kan vises status på hvor vi er i progresjonen?
- Er der andre prosesser vi kan se fremdrift på?
- Kanskje en tidsteller er lurt (kjørt i n min, 45 sec eller lignende)?

No er det bare å vente, hvor lenge skal man vente før man anser at programmet faktisk henger/har krasjet?

Tilleggsinfo 1t seinere:
- Minnebruk nede i 13 MB, og disk aktivitet 0%
- Ser ut til at Arkad 5 sitt kall til 3. parts programvare Siegfried for PRONOM har gått til ingenmannsland?

**Comment by solfeggietto** [comment]
Se vedlagt skjermdump av oppgavebehandling.
- Arkivverket app er rimelig inaktiv => disk aktivitet 0% fortsatt

Startet Droid v6.5.2 som no kjører PRONOM-analyse av innholdet: 
- Prosessor: 15,3%
- Minne: 245,9 MB
- Og ikke minst Disk: 17,5 MB/s

![Arkade5_vs_Droid_pronom](https://user-images.githubusercontent.com/622856/218069106-90391f72-f1e3-4426-9c9b-f232ef805fb0.png)

**Comment by solfeggietto** [comment]
Etter å ha kjørt Droid PRONOM analyse, prøver jeg Arkade 5 v2.8.0 igjen.
Denne gangen, etter nøyaktig samme kildemappe og målmappe med csv filnavn, så starter analyse dialog:
- Utfører formatanalyse 0 av 0 filer analysert.

Denne klient skal få stå på og kjøre i helgen - oppdaterer resultat når ferdig her i tråden.

![Arkade5_pronom_02](https://user-images.githubusercontent.com/622856/218107722-62893c48-3586-4b76-8e11-37437df00831.png)

**Comment by solfeggietto** [comment]
Problemet er bare at ganske umiddelbart forsvinner progress-hjulet og tekst:
- Tom dialogboks
- Bare "Lukk" knappen vises

Hva betyr dette:
- Krasjet testen?
- Hva vet Arkade 5 om status på 3. parts programvare Siegfried som gjør PRONOM-analysen?
- Finnes det noe logg noe sted?

![Arkade5_pronom_03](https://user-images.githubusercontent.com/622856/218108312-ca30821b-35a9-4e24-b911-35c7881a0a5e.png)

**Comment by solfeggietto** [comment]
Hva skjer med denne meldte feilen, som i praksis hindere bruk av Arkade 5 v2.9.0 for mange av de store uttrekkene?

Det er lite tilfredstillende at Arkade 5 tilsynelatende her ikke fungerer med PRONOM-analyse av en viss størrelse eller om der er andre egenskaper når det ikke virker?

Er det slik at store nok uttrekk faktisk ikke virker med PRONOM Filanalysen?
 - Har dere testet at det virker med store samlinger av filer i Pronom via 3. part Siegfried her?
 - Som vist i GitHub issue er der et kort blink med 0 av 0 filer da jeg testet (det konsentrerte jeg meg ikke om her, stirret ikke på skjermen i startfasen av jobben, så vet ikke, men antar samme progresjon)

No har jeg 2 uttrekk på 2 ulike PCer som bare henger på samme måte, ikke noe skjer i PRONOM filformat-analyse => 0% CPU og 0% diskbelegge, så disse jobbene er no døde

1. Innmeldt eksempel med mappe øverst på 360 GB med 266 mapper og 49 973 filer totalt 127 GB den mappen
2. Eksempel PC1 her no har 343 097 filer i rotmappe DOKUMENT totalt 127 GB den mappen
89 filer > 100 MB, største fil = 744 MB, minnebruk Arkade er no 1.83 GB
(typisk Documaster måten å ta Noark 5-uttrekk alt i en mappe dokumenter)
3. Eksempel PC2 her no har 842 647 filer i rotmappe DOKUMENT totalt 628 GB den mappen
439 filer > 100 MB, største fil = 1.4 GB, minnebruk Arkade er no 1.65 GB

Et annet Documaster-uttrekk hvor Arkade 5 v2.9.0 utførte PRONOM filanalyse med suksess
 - Eksempel på PC1 i går hadde 354 284 filer i rotmappe DOKUMENT totalt 130 GB den mappen
83 > 100 MB, største fil 987 MB

**Comment by solfeggietto** [comment]
Hei, testet igjen => 
 - Eksempel PC2 her no har 842 647 filer i rotmappe DOKUMENT totalt 628 GB den mappen 439 filer > 100 MB, største fil = 1.4 GB, minnebruk Arkade er no 1.65 GB

1. Valgte katalog DOKUMENT i et Noark 5-uttrekk
2. Valgte målmapper rapporter som andre steg etter klikket KJØR-knapp
3. Det kom absolutt ingen teller - går rett i ferdig modus, 0 % CPU, 0 % disk, noe RAM
4. Klikket LUKK og Verktøy dialog gikk ned

Dette ble prøvd etter å ha lukket tidligere kjørt Arkade, så ikke noe henge fra forrige kjøring.

![Arkade5_v2 9 0_b02](https://user-images.githubusercontent.com/622856/219409048-085f57d2-57c3-45a6-a10c-1644c8b2beed.png)

**Comment by lhSunde** [comment]
Fikset i versjon 2.9.1
