### ISSUE TITLE
Filenames with more than one period fails

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#159]
I have an extraction where the files are (strangely enough) named as following:
![image](https://user-images.githubusercontent.com/1849298/219016524-e4be16c4-f85a-457b-8970-d087650718f5.png)

Giving the following result in the report:
![image](https://user-images.githubusercontent.com/1849298/219016712-f0fc7d64-5253-4552-b1ce-fbcf61f558b9.png)

Please consider allowing more than one period in filenames.

**Comment by erikaaberg** [comment]
Vi tror ikke dette gjelder generelt. Vi har testet (med versjon 2.9.0) diverse filnavne med og uten flere punktum.  Feilmeldinga tyder på at at "noe" tolker de første tegn etter punktum som format. Det kan være Arkade, eller det kan være den programvare som har produsert selve uttrekket. I arkivstruktur.xml skal det stå <format>pdf</format>. Gjør det det? Hvis ja: Er det mulig å få flere detaljer (kopi av relevante deler av arkivstruktur.xml og liste over relevante filer i "dokumenter" mappa)?

**Comment by smult** [comment]
Ser ut til at dette var en feil i <format>-taggen. Har mottatt en rekke uttrekk nå for Visma-systemer, og de er gjennomgående merket <format>PDF/A</format>. Dette feiler.
Så saken kan lukkes og sees bort i fra, men synes vel enten PDF/A burde være en godkjent variant her. Visma har av en eller annen grunn startet å legge dette i uttrekkene, så her bør det vel informeres til Visma.
