### ISSUE TITLE
Linux Port

### ISSUE THREAD

**Issue by erikaaberg** [arkivverket/arkade5#16]
Inkl. .NET tilpasninger i den grad det er nødvendig. Og fjerning av bindinger til Visual Studio utviklingsverktøy o.a. Backend prioriteres fremfor GUI. Linux GUI kan bygges ved hjelp av API.

**Comment by joafug** [comment]
Det er laget en kommandolinje-versjon:
[(http://arkade.arkivverket.no/no/latest/Systemdokumentasjon.html#arkade-api)]

GUI blir ikke prioritert nå.

Det er laget veiledning for tilpasning til andre plattformer:
[(http://arkade.arkivverket.no/no/latest/Systemdokumentasjon.html#porting-to-other-platforms)]
