### ISSUE TITLE
PRONOM liste over zip innhold blir ikke med hvis fil-endelse ikke er zip/rar osv.

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#160]
To konkrete bugs i Arkade 5 v2.9.0 under verktøy Filformatanalyse

1. En pakket fil (som .zip) får ikke analysert og tellt opp innholdsfiler hvis filendelse ikke er zip eller tilsvarende pakketyper
2. En zip fil har zip filendelse blir tellt 2 ganger i både filformatinfo og filformatinfo-statistikk

Vedlegg
 - zip fil som er testet med, inklusig testet som .xls filendelse
 - Skjermdump fra filformatinfo og filformatinfo-statistikk for begge to feilsituasjoner over

<img width="224" alt="Arkade5_v2 9 0_a03" src="https://user-images.githubusercontent.com/622856/219671764-4577eb16-9158-430b-8370-1014684037d8.png">
<img width="770" alt="Arkade5_v2 9 0_a04" src="https://user-images.githubusercontent.com/622856/219674924-b278b390-a197-445f-9efb-0729ae06411d.png">

[12345678.zip.xlsx](https://github.com/arkivverket/arkade5/files/10767356/12345678.zip.xlsx)
[12345678.zip](https://github.com/arkivverket/arkade5/files/10767357/12345678.zip)

**Comment by erikaaberg** [comment]
Fixet i 2.9.1
