### ISSUE TITLE
Validering av arkivformat app krasjer ved noen store uttrekk

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#161]
Arkade 5 v2.9.1 verktøy "Validering av arkivformat" krasjer ved noen sture uttrekk.

Eksempel som krasjer
 - Noark 5-uttrekk, kjørt test "validering av arkivformat" av mappe "DOKUMENTER"
 - Mappen består av 888 678 filer alle i rotmappen DOKUMENTER, totalt 716 GB
 - Der 559 filer > 100 MB, største fil = 987 MB
 - Alle disse største filer er PDF, untatt en som er zip-fil
 - Vedlagte skjermbilder viser start og at disk jobber jevnt og trutt mot maks hastighet
 - Men 2 siste bilder viser at ting stopper opp, med et lite peak 1 min etter første stopp aktivitet

1. Hvordan kan vi feilsøke slike situasjoner (her konkret køring av 3. parts verktøy veraPDF og samhandlingen med hovedapp Arkade)?
2. Finnes der logger på klienten i program-mappe for Arkade?
3. Eller må vi builde vår egen versjon av Arkade 5 for å feilsøke direkte i Visual Studio på det selv?

Se vedlagte skjermbilder
![CRASH-1 1_1519_012_pdf-valideringsrapport](https://user-images.githubusercontent.com/622856/223406252-e4593d26-1646-48db-acab-6530b7d4911c.png)
![CRASH-1 2_1519_012_pdf-valideringsrapport](https://user-images.githubusercontent.com/622856/223406267-f6dd53b6-35f3-4f2a-9fec-88f82dc71327.png)
![CRASH-1 3_1519_012_pdf-valideringsrapport](https://user-images.githubusercontent.com/622856/223406283-6647fa05-724c-48aa-9e66-69dd89dfdfda.png)
![CRASH-1 4_1519_012_pdf-valideringsrapport](https://user-images.githubusercontent.com/622856/223406295-4c12e8b3-1441-4698-b105-42a55b79c90f.png)
![CRASH-1 5_1519_012_pdf-valideringsrapport](https://user-images.githubusercontent.com/622856/223406312-6aeaf672-7e5c-44be-94cd-44333f437f47.png)

**Comment by erikaaberg** [comment]
Ja - -  denne er ikke så grei. Vi ser rett og slett ikke hvordan vi på en (rimelig) enkel måte kan fange opp hengsituasjoner i VeraPDF. Så vi kaster rett og slett inn håndkleet. Beklager. Det eneste råd vi kan gi er å kjøre VeraPdf separat og se om det er lettere å diagnostisere. Saken lukkes.

**Comment by solfeggietto** [comment]
Arkade 5 v2.10.0 fungere på samme måte, noen store Noark 5-uttrekk 500 GB+ med noen PDF-filer opp mot 1 GB, fører til
- Arkade 5 krasjer (appen er plutselig lukket uten no spor)
- Etter at PDF/A validator er startet og kjørende med aktivitet prosessor og mot disken
- Siden dette tar lang tid og vi ikke har satt på videopvervåkning eller annet av skjerm eller app så vet vi ikke mer no

Javel, en ting er at Arkade 5 ikke har kontroll på 3-parts programvare veraPDF som kalles opp, men hvordan kan et kallt til en ekstern app føre til at Arkade 5 selv krasjer? Dette må vel være mulig å debugge og finne ut av, og i det minste rapportere hvor og hva som er tilstand til at hele Arkade 5 app krasjer og stopper/forsvinner uten forklaring?
