### ISSUE TITLE
Arkade 5 v2.9.1 krasjer hvis sjekksum er tom for løpende- og offentlig journal

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#165]
Case: arkivuttrekk.xml har med fil-elementer
 - loependeJournal.xml
 - offentligJournal.xml

Men value for sjekksum er tomt element.

Arkade 5 v2.9.1 må IKKE krasje bare fordi verdi på sjekksum mangler
 - Feilretting: la testene fullføre uten de 2 journaler med

Jeg testet manuelt med å 
 - lage 2 journaler.xml filer over med kun header
 - altså ingen journalregistrering elementer
 - la til sjekksummer for de 2 filene manuelt i en kopi av uttrekket, da i arkivuttrekk.xml
 - Arkade 5 v2.9.1 fullførte tester vellykket, og bare rapporterte at obligatoriske elementer for journalregistrering manglet
 - Altså slik testene skulle vært når sjekksummer manglet også i utgangspunktet, bare meldt at de manglet og testet alt annet videre

```
System information:
Arkade version: 2.9.1
.NET CLR: 6.0.14
Total disk space: 2000381014016 (1907711 MB)
Available disk space: 739417624576 (705163 MB)

Stack trace:
System.IO.FileNotFoundException: Could not find file 'G:\arkiv-noark5\1529\1529_018_E-1507-2023-0009\content\sip\content\loependeJournal.xml'.
File name: 'G:\arkiv-noark5\1529\1529_018_E-1507-2023-0009\content\sip\content\loependeJournal.xml'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileInfo.OpenRead()
   at Arkivverket.Arkade.Core.Util.Sha256ChecksumGenerator.GenerateChecksum(String pathToFile) in (..)\Arkivverket.Arkade.Core\Util\Sha256ChecksumGenerator.cs:line 26
   at Arkivverket.Arkade.Core.Testing.Noark5.Structure.N5_02_ValidateAddmlDataobjectsChecksums.Test(Archive archive) in (..)\Arkivverket.Arkade.Core\Testing\Noark5\Structure\N5_02_ValidateAddmlDataobjectsChecksums.cs:line 36
   at Arkivverket.Arkade.Core.Base.Noark5.Noark5TestEngine.RunStructureTests(TestSession testSession) in (..)\Arkivverket.Arkade.Core\Base\Noark5\Noark5TestEngine.cs:line 127
   at Arkivverket.Arkade.Core.Base.Noark5.Noark5TestEngine.RunTestsOnArchive(TestSession testSession) in (..)\Arkivverket.Arkade.Core\Base\Noark5\Noark5TestEngine.cs:line 35
   at Arkivverket.Arkade.Core.Base.ArkadeApi.RunTests(TestSession testSession) in (..)\Arkivverket.Arkade.Core\Base\ArkadeApi.cs:line 94
   at Arkivverket.Arkade.GUI.ViewModels.TestRunnerViewModel.RunTests() in (..)\Arkivverket.Arkade.GUI\ViewModels\TestRunnerViewModel.cs:line 432

```

**Comment by solfeggietto** [comment]
Workaround som hindrer at Arkade 5 krasjer helt før noe er blitt testet
 - altså hindre at tomt xml element for sjekksum av filen som er i Arkivstruktur.xml, men ikke finnes fører til Arkade krasj
 - => Ta vekk Testpunkt N05.02 - Validering av sjekksummer
 - => Du må da teste manuelt validering av alle andre sjekksummer som Arkade 5 normalt sjekker i punkt N05.02

Det viser seg at Arkade 5 krasjer på
 - Noark 5 Testpunkt N5.02 - Validering av sjekksummer
 - Se skjermdumper under at testpunktet tas vekk kryss for før test
 - Arkade 5 testene for Noark 5 fullføres (Lager rapport + Testingen er fullført)
 - altså at Arkade 5 som app ikke krasjer (vi vil alltid kjøre ferdig test og så vurdere resultat, ikke at Arkade 5 krasjer eller avbryter)
 - Skjermumpene viser også at følgende Noark 5 tester feiler (som forventet):
 - N05.01 Kontroll av eksistens for XML-filene
 - N05.02 Validering av XML i henhold til skjema

![1529_018_testrapport_debug-1 1](https://user-images.githubusercontent.com/622856/231474973-b9d12cf3-622e-472c-bc64-45d1fbf3e180.png)
![1529_018_testrapport_debug-1 2](https://user-images.githubusercontent.com/622856/231474986-bf95e80a-4f2c-4b07-a21b-2bc4222a969e.png)
![1529_018_testrapport_debug-1 3](https://user-images.githubusercontent.com/622856/231475005-76045388-487e-455b-ab64-36933231d36c.png)

**Comment by lhSunde** [comment]
Hei!

Krasjer Arkade, eller får du en feilmelding i Testvinduet før testkjøringen avbrytes?
![image](https://user-images.githubusercontent.com/53507304/232687565-62b30108-3aef-4973-8043-80fc3b05c06b.png)
Man kan selvsagt diskutere hvorvidt testingen skal avbrytes eller ikke ved slike feil. @joergen-vs @erikaaberg

Jeg forsøkte å fjerne sjekksumverdien for lopendeJournal.xml og offentligJournal.xml fra arkivuttrekk.xml - det resulterte i en feilmelding under testkjøring, men ingen avbrytelse av testene. 

Er du sikker på at **filene** i arkivuttrekket "loependeJournal.xml"/"offentligJournal.xml" heter nettopp dette, og at de er lokalisert ved siden av "arkivuttrekk.xml"? 
Eksempelet under vil resultere i feilen du beskriver, gitt at journalfilene er dokumentert i arkivuttrekk.xml.
![image](https://user-images.githubusercontent.com/53507304/232689172-25da4632-9806-4889-a4c0-0fb08a9da374.png)

**Comment by lhSunde** [comment]
Hei igjen!

Grunnen til at jeg spurte om det var en krasj eller en avbrutt testkjøring er at jeg tenker på en core dump eller en uhåndtert unntakssituasjon (Exception) når det snakkes om en krasj. Dette er også grunnen til at jeg skriver dette:
> Man kan selvsagt diskutere hvorvidt testingen skal avbrytes eller ikke ved slike feil.

Jeg har kanskje en litt snever definisjon av begrepet, burde nok informert om min forståelse av det :)

Men ja, C# Exception forklarer problemet greit: 
> Could not find file 'G:\arkiv-noark5\1529\1529_018_E-1507-2023-0009\content\sip\content\loependeJournal.xml'

Filen finnes ikke, derfor kastes det en Exception.

Tittelen på dette issuet er imidlertid "Arkade 5 v2.9.1 krasjer hvis sjekksum er tom for løpende- og offentlig journal".
Dette hevdes også i dine to første kommentarer:
> Arkade 5 v2.9.1 må IKKE krasje bare fordi verdi på sjekksum mangler

> Workaround som hindrer at Arkade 5 krasjer helt før noe er blitt testet
> * altså hindre at tomt xml element for sjekksum av filen som er i Arkivstruktur.xml, men ikke finnes fører til Arkade krasj

Det er dette jeg prøver å oppklare i resten av den forrige kommentaren min.
Basert på både feilmelding og egen testing og mistenker jeg at krasjen eller den avbrutte testkjøringen skyldes at filene mangler, ikke at sjekksumfeltet er tomt. Dersom filene eksisterer og sjekksumfeltet er tomt, vil testkjøringen fullføres med testresultat som indikerer at dokumenterte sjekksummer ikke er gyldige.

**Comment by solfeggietto** [comment]
Det er en tålmodighetsprøve å drive support, når den som melder feil ofte er upresis :-).

Jeg formulerte meg feil, det er jo Arkade 5 testen som "krasjer" og kaster "exception" som da logges i Arkade 5 temp arbeidsmappe som "arkade-error-<datostempel>.log og som jeg limte med et par ganger over.

Angående hva Arkade 5 bør gjøre når det oppdages problemer med Løpende og Offentlig journal er jeg ikke i tvil om at dette ikke utløser at Arkade 5 bør stoppe testene. I stedet bør exception tas til etterretning og problemet/feilen skrives i testrapporten, mens Noark 5-testene av hovedfilen i et Noark 5-uttrekk arkivstruktur.xml gjøres til fulle inklusiv kryssjekker mot \dokumenter mappen. Det samme gjelder endringslogg, hvis der er problemer dokumenter feilene og kjør ferdig test av hovedinnhold Noark 5.

Dette slik at vi ikke går tilbake til arkN4 problematikken at man ved 10, 100 eller 1000 feil må teste 10, 100 eller 1000 ganger etter hver retting (eller så mange ganger der er feil). Det er IT-rådgiver i depot som må ta beslutning basert på hva tester sier, slik at testene må fullføres så sant det er mulighet for det og dokumentere hva man finner.

Under oppsummert alle testene som jeg har gjort med meldt problematikk:

1529_018_debug-0-error.txt

# Tests #

Noark 5 v2.9.1
- Validerer unzipped .tar fil med PKZIP unzipper
- Arkade 5 Noark 5 test krasjer i starten av Noark 5-test
- Arkade selv krasjer ikke, men peker på log fil med feil:
- System.IO.FileNotFoundException: Could not find file 
- Det viser seg at Noark 5 test N05.02 - Validering av sjekksummer
- Som er sjekksummer av xml-filene i rot av Noark 5-uttrekket
- Inklusiv loependeJournal.xml & offentligJournal.xml

1529_018_debug-1.txt

# Tests #

Noark 5 v2.9.1
- Validerer unzipped .tar fil med PKZIP unzipper
- På en kopi, legger til loependeJournal.xml & offentligJournal.xml fra annen VSA, men uten elementer under toppseksjon
- Redigerer Arkivuttrekk.xml legger til sjekksum for de 2 manglende filene over, som var der allerede med tom sjekksum
- Test rapport gir invalid/manglende elementer for de 2 journalene (som forventet siden de er tomme for oppføringer)

1529_018_debug-2.txt

# Tests #

Noark 5 v2.9.1
- Validerer unzipped .tar fil med PKZIP unzipper
- Noark 5 test startes uten test N05-02 - Validering av sjekksummer
- Fullføres og rapport viser feilene
- N05.01 - Kontroll av eksistens for XML-filene
- N05.03 - Validering av XML i henhold til skjema

1529_018_debug-3.txt

# Tests #

Noark 5 v2.9.1
- Validerer unzipped .tar fil med PKZIP unzipper
- På en kopi, redigerer Arkivuttrekk.xml og fjerner file seksjoner der for loependeJournal.xml og offentligJournal.xml
- Test rapport uten direkte feil mot offentlig eller løpende journal, men det i stedet "Kunne ikke lese fra en eller flere journalfiler"

1529_018_debug-4-error.txt

# Tests #

Noark 5 v2.9.1
- Validerer unzipped .tar fil med PKZIP unzipper
- Arkade 5 Noark 5 test krasjer i starten av Noark 5-test
- Arkade selv krasjer ikke, men peker på log fil med feil:
- System.NullReferenceException: Object reference not set to an instance of an object. (prøver å lese sjekksum element verdi, men den er tom) 
- Det viser seg at Noark 5 test N05.02 - Validering av sjekksummer
- Som er sjekksummer av xml-filene i rot av Noark 5-uttrekket
- Inklusiv loependeJournal.xml & offentligJournal.xml

System information:
Arkade version: 2.9.1
.NET CLR: 6.0.15
Total disk space: 2000381014016 (1907711 MB)
Available disk space: 739528757248 (705269 MB)

Stack trace:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Arkivverket.Arkade.Core.Testing.Noark5.Structure.N5_02_ValidateAddmlDataobjectsChecksums.CreateTestResult(Boolean checksumsAreEqual, String generatedChecksum, String expectedChecksum, String fileName, String checksumAlgorithm) in (..)\Arkivverket.Arkade.Core\Testing\Noark5\Structure\N5_02_ValidateAddmlDataobjectsChecksums.cs:line 77
   at Arkivverket.Arkade.Core.Testing.Noark5.Structure.N5_02_ValidateAddmlDataobjectsChecksums.Test(Archive archive) in (..)\Arkivverket.Arkade.Core\Testing\Noark5\Structure\N5_02_ValidateAddmlDataobjectsChecksums.cs:line 38
   at Arkivverket.Arkade.Core.Base.Noark5.Noark5TestEngine.RunStructureTests(TestSession testSession) in (..)\Arkivverket.Arkade.Core\Base\Noark5\Noark5TestEngine.cs:line 127
   at Arkivverket.Arkade.Core.Base.Noark5.Noark5TestEngine.RunTestsOnArchive(TestSession testSession) in (..)\Arkivverket.Arkade.Core\Base\Noark5\Noark5TestEngine.cs:line 35
   at Arkivverket.Arkade.Core.Base.ArkadeApi.RunTests(TestSession testSession) in (..)\Arkivverket.Arkade.Core\Base\ArkadeApi.cs:line 94
   at Arkivverket.Arkade.GUI.ViewModels.TestRunnerViewModel.RunTests() in (..)\Arkivverket.Arkade.GUI\ViewModels\TestRunnerViewModel.cs:line 432

**Comment by solfeggietto** [comment]
Jeg er enig i definisjonen av "krasj", men i mitt hode hadde hele Arkade 5 krasjet da jeg skreiv GitHub Issue.
Så jeg burde skrevet at Arkade 5 avbrøt Noark 5-testen etter en Exception i stedet for å skrive at Arkade 5 krasjet!

**Comment by lhSunde** [comment]
Vi er alltid takknemlige for at feil blir rapportert! Men det er viktig for historikken at årsaken til feilene kommer klart frem :)

Mange takk for utdypende tester - det viser seg at du har helt rett! Jeg har også gjort litt mer testing her; Noark5-valideringen avbrytes i tre tilfeller - se under.

Gitt en sjekksum-property i arkivuttrekk.xml:
```xml
1:  <property name="checksum">
2:   <properties>
3:    <property name="algorithm">
4:     <value>SHA256</value>
5:    </property>
6:    <property name="value">
7:     <value>en sjekksumverdi</value>
8:    </property>
9:   </properties>
10: </property>
``` 

1. Som du oppdaget; dersom value-property mangler (linje 6-8)
2. Dersom algorithm-property mangler (linje 3-5)
3. Dersom hele sjekksum-propertyen mangler (linje 1-10)

Dette er rapportert inn i JIRA-sak ARKADE-711.

**Comment by solfeggietto** [comment]
Spørsmål

1. For sikkerhets skyld spør jeg også om den første testen også er med i JIRA-sak ARKADE_711? Altså det at Arkivuttrekk.xml peker på løpende og offentlig journal .xml filer som ikke finnes? Dette bør bare meldes som en feil, og hele Noark 5-testen kjøres forøvrig som da hovedsaklig tester på Arkivstruktur.xml og dokumentene.

2. Er innrapporterte JIRA for Arkade offentlig tilgjengelig for å følge med på, eller er det et lukket system for utvikler og oppdragsgiver Arkivverket?

# Test: 1529_018_debug-0-error.txt #

Noark 5 v2.9.1
- Validerer unzipped .tar fil med PKZIP unzipper
- Arkade 5 Noark 5 test krasjer i starten av Noark 5-test
- Arkade selv krasjer ikke, men peker på log fil med feil:
- System.IO.FileNotFoundException: Could not find file 
- Det viser seg at Noark 5 test N05.02 - Validering av sjekksummer
- Som er sjekksummer av xml-filene i rot av Noark 5-uttrekket
- Inklusiv loependeJournal.xml & offentligJournal.xml

**Comment by lhSunde** [comment]
1. Ja; N5.02 skal ikke lenger avbryte testing dersom filene som pekes på mangler - en feilmelding skal vises under testresultater.
2. JIRA-tavla er nok ikke offentlig - det er primært ment som en kanal mellom utviklere og oppdragsgivere. Det er nok mest ryddig at brukere melder inn feil her på GitHub, og at det er oppdragsgiver som videre dirigerer hvilke saker som velges for utvikling. (Slik sett har jeg muligens gått litt utenfor mitt mandat i denne saken... 😟)
