### ISSUE TITLE
Varsel om sårbarhet oppdaget i Arkade 5

### ISSUE THREAD

**Issue by joergen-vs** [arkivverket/arkade5#168]
Det er oppdaget en sårbarhet i Arkade 5, versjoner f.o.m. 2.5.0 (utgitt 04.11.2021) t.o.m. 2.10.0 (utgitt 16.05.2023).

Ved innlasting av arkivuttrekk med arkivtype Siard (Siard-uttrekk) vil Arkade 5-versjoner som er berørt av sårbarheten, rekursivt kopiere alle filer og kataloger som ligger i samme katalog som uttrekksfilen (.siard-filen) til sitt temporære arbeidsområde. Dersom det opprettes en informasjonspakke (SIP/AIP) fra uttrekket, vil alle filene/katalogene i temporærområdet bli inkludert, selv om de ikke nødvendigvis tilhører Siard-uttrekket som pakkes.

Pakking av Siard-uttrekk kan gjøres trygt inntil utbedret Arkade-versjon utgis ved at uttrekksfilen (.siard) som skal prosesseres, ligger separat i en egen katalog evt. kun sammen med innhold som tilhører det aktuelle Siard-uttrekket (filer som det refereres til i uttrekksfilen).

Se mer detaljer i vedlegget.
[Sårbarhet_Arkade5_v2.5-v2.10.pdf](https://github.com/arkivverket/arkade5/files/11736415/Sarbarhet_Arkade5_v2.5-v2.10.pdf)

**Comment by joergen-vs** [comment]
Vi jobber med å utbedre sårbarheten og kommer tilbake med mer informasjon når det er klart.

**Comment by Swoy** [comment]
Dette problemet drar meg tilbake til et funksjonsønske vi hadde for to år siden i et møte med utvikleren. Det ble da nevnt at vi gjerne skulle sett en mulighet for å forfatte innholdet i pakken på en mer ordnet måte. For å gi et overordnet eksempel, og for ikke å gjøre dette til en utvidet digresjon, her er et bilde:

![image](https://github.com/arkivverket/arkade5/assets/5272077/6b2de9b8-4011-4931-97c9-50ad98bfb0dc)

Trykker du redaktør, får du opp følgende dialog/sidevisning:

![image](https://github.com/arkivverket/arkade5/assets/5272077/afd16991-3a2f-4231-a37b-13671b78168d)

**Comment by innocentlypassingby** [comment]
> Jeg antar dette kun gjelder når du velger "Velg fil"?

Stemmer.

**Comment by joergen-vs** [comment]
> Jeg antar dette kun gjelder når du velger "Velg fil"?

Det stemmer.

**Comment by joergen-vs** [comment]
Løst i hotfix 2.10.1,
https://github.com/arkivverket/arkade5/releases/tag/v2.10.1
