### ISSUE TITLE
Arkade benytter restriksjoner fra NOARK-5 versjon 4.0 på arkivuttrekk produsert iht Versjon 5.0

### ISSUE THREAD

**Issue by SteinarAbrahamsen** [arkivverket/arkade5#173]
Restriksjoner på tillatte verdier for sak og journalstatus ble fjernet Noark 5 versjon 5.0.  Arkade benytter restriksjonene fra versjon 4.0. Dette er spesielt et problem i forhold til journalstatus "Utgår". 

Forslag: Vi ber om at det forhold blir rettet og at det valgfritt (konfigurerbart) hvilken verdi som representerer utgåtte registeringer.

**Comment by joergen-vs** [comment]
Arkade forholder seg til gjeldende standard, hvor krav til kode ikke lenger ligger i xml-skjemaet metadatakatalog.xsd. Men kravet består i kravene i standarden, se 3.2.19.
Dette spørsmålet bør derfor tas opp med gruppen som forvalter standarden [lenke til saker her](https://github.com/arkivverket/noark5-standard/issues)
