### ISSUE TITLE
Fleksibilitet i fil lokasjoner - generelt

### ISSUE THREAD

**Issue by erikaaberg** [arkivverket/arkade5#18]
Det bør være mulig å angi hvor div. filer ligger - dersom de ikke finnes, det gjelder:
         - addml.xml / arkivstruktur.xml
         - info.xml
         - NOARKIH.XML
         - data (inkl. å kunne overstyre absolutt path, men ut-pakke MÅ ha relativ path)

**Comment by erikaaberg** [comment]
Gjelder også .tar-filer inn.

**Comment by rholte** [comment]
Det burde være mulig å konfigurere hvor Arkade5 sin arbeidskatalog skal ligge. Default ser ut til å være %HOMEPATH%\Arkade. Personlig liker jeg ikke plasseringen og ville ha foretrukket heller D:\Arkade

**Comment by erikaaberg** [comment]
Enig. Det er ført opp på forbedringslista til høsten.

**Comment by joafug** [comment]
Dette er løst. Er nå mulig å velge arbeidsområde.
