### ISSUE TITLE
Lite lesbar status tekst (fra Tormod Engebu)

### ISSUE THREAD

**Issue by erikaaberg** [arkivverket/arkade5#19]
**Statusteksten om at pakken er lagret, og listing av mappenavnet, etter endt laging av pakke er også "trødd" sammen i et veldig smalt felt til venstre i skjermbildet under knappene nederst i vinduet. Bør utvidet, så det blir litt mer lesbart.**

**Comment by joafug** [comment]
@smult
Denne står på gjøremålsliste

Ref: Arkade-138
