### ISSUE TITLE
Mer info ved lesing av arkiv

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#2]
Ved innlesing av større arkiver er det minimalt med info under innlesing. Hadde vært kjekt med en eller annen form for tilbakemelding i form av hva programmet gjør for øyeblikket, eller en progressbar e.l. Nå snurrer bare ikonet evig, og jeg vet ikke om programmet har hengt seg, eller om det fortsatt gjør noe.
(Gjør forsøk med et arkiv, Acos Websak, på 97GB i en tar-fil)

**Comment by erikaaberg** [comment]
Relatert: Ved kontroll av sjekksummer - ses ingentng under "Arbeider med fil - - ". Her burde det stå hvilkne sjekksum som for øyeblikket kontrolleres.

**Comment by joafug** [comment]
Dette er lagt inn i gjøremålsliste.
Ref: Arkade-138
