### ISSUE TITLE
Ønske om å bevare kontekst - om metadata

### ISSUE THREAD

**Issue by erikaaberg** [arkivverket/arkade5#22]
Fint om det kunne være en config fil som lagret metaadata (arkivskaper etc.), der verdier ble brukt som standard/forhåndsutfylt i felt som skal redigeres manuelt.

**Comment by solfeggietto** [comment]
Mange kommuner har IT-driftsorganisasjon for sin region som drifter felles databaser og løsninger. Da vil gjerne en IT-tjeneste gjennomføre uttrekk (med støtte av leverandør). Mulighet for profildokument (config-fil) pr. arkivskaper vil a være meget arbeidsbesparende og gi bedre kvalitet/gjenbruk av samme data.

**Comment by joafug** [comment]
Dette er en større oppgave som kan ta noe tid.
Må spekkes opp og priorteres.

Lagt inn i gjøremålsliste.
Ref: Arkade-204
