### ISSUE TITLE
Ønske om å bevare kontekst under kjøring - for å kunne fortsette

### ISSUE THREAD

**Issue by erikaaberg** [arkivverket/arkade5#23]
Typisk: Man kjører (evt. lenge) i en test - men må fixe noe underveis. Ønske om å kunne gjenoppta der man slapp.

**Comment by joafug** [comment]
Det er ikke lagt opp for dette i nåværende versjon av Arkade.
Fordrer mest sannsynlig større omstrukturering. 
Må eventuelt gjøres senere. Ikke prioritert

Lagt inn i gjøremålsliste.
Ref: Arkade-195
