### ISSUE TITLE
Mulighet for å kunne skru tester av og på

### ISSUE THREAD

**Issue by erikaaberg** [arkivverket/arkade5#25]
Når uttrekket er for grumsete i forhold til standarder, og ofte der dette ikke kan gjøres noe med.

Ønske om et "panel" e.l. der man kan velge av/på brytere for hvilke tester som skal kjøres (og evt. hvilke feil som skal logges)

**Comment by joafug** [comment]
Det er ikke lagt opp for dette i nåværende versjon av Arkade.
Større sak som kan ta noe tid.

Lagt inn i gjøremålsliste.
Ref: Arkade-196
