### ISSUE TITLE
Angivelse av prosesser for flate filer

### ISSUE THREAD

**Issue by PetterBAR** [arkivverket/arkade5#29]
I henhold til ADDML 8.2, skal filnivået i prosessangivelsen gis ved navnet på filen, ikke fildefinisjonens.
<flatFileProcesses flatFileReference="name til aktuell flatFile">
Arkade 5 forutsetter name til en flatFileDefinition, ikke name til en flatFile slik som angitt i standarden.

Det vil i teorien kunne utføres prosesser på feil fil når en fildefinisjon er felles for flere flate filer. I Norge er det et en-til-en-forhold mellom flatFile og flatFileDefinition, så i praksis vil ikke dette skje.

I de tilfellene hvor flatFile og flatFileDefinition har samme name, vil ikke brukeren merke avviket.

Når standarden følges, utføres ikke prosessen og Arkade 5 gir ingen melding om at noen prosesser ikke har blitt utført på grunn av manglende referanse.

**Comment by PetterBAR** [comment]
En liten kommentar til denne.
I praksis tvinges nå den som lager ADDML-beskrivelser, til å angi samme name på flatFileDefinition som på den flatFile'en som den tilhører.
Skjer ikke dette, vil ikke de aktuelle prosessene utføres og brukeren får ikke beskjed om at de ikke har blitt utført. 
Det bør i det minste dokumenteres tydelig at Arkade 5 ikke følger bruken av ADDML på dette området og hva som er faren ved å ha forskjellige name.

**Comment by joafug** [comment]
Dette må rettes.
I første omgang en pressisering i dokumentasjon.
Endring i Arkade må spesifiseres opp.

Lagt inn i gjøremålsliste.
Ref: Arkade-199
