### ISSUE TITLE
Innlesing av NOARK5 - addml.xml heter ikke alltid addml.xml

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#3]
Programmet feiler ved forsøk på lesing av .tar-fil hvor addml.xml heter arkivuttrekk.xml. Dette navnet går igjen i mange uttrekk, så enten bør det legges inn som alternativ, eller så må det være mulig å manuelt velge hvilken xml-fil i uttrekket som er addml-fila. Kunne også vært løst ved å sjekke xml-filene og se hvilken fil som er addml i henhold til syntax i xml'en eller referansen til xsd-fila.

**Comment by smult** [comment]
Et annet problem i samme leia er at strukturen som forventes av Arkade 5 ikke henger på greip med realiteten. Forventet struktur samsvarer med Essarch-strukturen, og det er jo bra, men det bør være mulig å enten søke etter filer, eller endre mappe for hvor filene ligger, slik at Arkade finner filene i uttrekket. Den forventer vel å finne addml.xml i administrativ_metadata, men det er jo ikke alltid tilfelle at den ligger der, i allefall ikke i kommunalt produserte uttrekk. Hvis dette er et absolutt krav i statlige leveringer, så passer det jo veldig bra. Men litt fleksibilitet burde være mulig å få til.

**Comment by erikaaberg** [comment]
ENIG! Får det ikke til første versjon, men legges inn som ønske til neste. Setter denne foreløpig som "SOLVED".
