### ISSUE TITLE
Rapporterer Arkade 5 Noark 5-tester per arkivdel?

### ISSUE THREAD

**Issue by PetterBAR** [arkivverket/arkade5#30]
Ref. at det blir uoversiktlige samleresultater fra ArkN4 når uttrekk inneholder flere arkivdeler, lurer jeg på om resultat per arkivdel er ivaretatt i Arkade 5.
Jeg har ikke fått testet på Noark 5-uttrekk, ellers kunne jeg ha funnet det ut selv.

**Comment by erikaaberg** [comment]
I Noark 5-tester der dette (for mange av testene) er angitt – gis resultatet per arkivdel der det er spesifisert.
