### ISSUE TITLE
Unike ID-er

### ISSUE THREAD

**Issue by erikaaberg** [arkivverket/arkade5#34]
Forbedring av tester rundt unike ID-er.

**Comment by petterreinholdtsen** [comment]
Hva testes i dag, og hva mangler?

**Comment by joafug** [comment]
Kontroll på at alle systemidentifikasjoner i arkivstrukturen er unike. Det kontrolleres at alle forekomster av elementet systemID i arkivstruktur.xml kun forekommer en gang.

Antall systemidentifikasjoner som ikke er unike kan angis slik:
Antall systemidentifikasjoner som ikke er unike: NN

Ligger i gjøremålsliste.
Ref: Arkade-28
