### ISSUE TITLE
Ukjent datatype "time" i Noark-4

### ISSUE THREAD

**Issue by joergen-vs** [arkivverket/arkade5#35]
---------------------------
Unexpected error!
---------------------------
Use Ctrl+C to copy this error message and send it to arkade5@arkivverket.no

System information:
Arkade version: 0.0.0.0
OS: Microsoft Windows 7 Professional 
OS Version: 6.1.7601.65536
.NET Framework: 394806
.NET CLR: 4.0.30319.42000
Total physical memory: 34242400256 (32656 MB)
Available physical memory: 19491545088 (18588 MB)
Total virtual memory: 2147352576 (2047 MB)
Available virtual memory: 1647616000 (1571 MB)
Total disk space: 120031539200 (114470 MB)
Available disk space: 7369166848 (7027 MB)

Stack trace:

Arkivverket.Arkade.Core.Addml.Definitions.AddmlDefinitionParseException: Unknown datatype time
   ved Arkivverket.Arkade.Core.Addml.Definitions.AddmlDefinitionParser.CreateFieldType(fieldType fieldType) i C:\Users\jorvik\Source\Repos\arkade5\src\Arkivverket.Arkade\Core\Addml\Definitions\AddmlDefinitionParser.cs:linje 111
   ved Arkivverket.Arkade.Core.Addml.Definitions.AddmlDefinitionParser.PopulateFieldTypes() i C:\Users\jorvik\Source\Repos\arkade5\src\Arkivverket.Arkade\Core\Addml\Definitions\AddmlDefinitionParser.cs:linje 75
   ved Arkivverket.Arkade.Core.Addml.Definitions.AddmlDefinitionParser..ctor(AddmlInfo addmlInfo, WorkingDirectory workingDirectory) i C:\Users\jorvik\Source\Repos\arkade5\src\Arkivverket.Arkade\Core\Addml\Definitions\AddmlDefinitionParser.cs:linje 35
   ved Arkivverket.Arkade.Identify.TestSessionFactory.NewSession(WorkingDirectory workingDirectory, ArchiveType archiveType, Uuid uuid) i C:\Users\jorvik\Source\Repos\arkade5\src\Arkivverket.Arkade\Identify\TestSessionFactory.cs:linje 73
   ved Arkivverket.Arkade.Identify.TestSessionFactory.NewSession(ArchiveDirectory archiveDirectory) i C:\Users\jorvik\Source\Repos\arkade5\src\Arkivverket.Arkade\Identify\TestSessionFactory.cs:linje 36
   ved Arkivverket.Arkade.Core.ArkadeApi.RunTests(ArchiveDirectory archiveDirectory) i C:\Users\jorvik\Source\Repos\arkade5\src\Arkivverket.Arkade\Core\ArkadeApi.cs:linje 32
   ved Arkivverket.Arkade.UI.ViewModels.TestRunnerViewModel.RunTests() i C:\Users\jorvik\Source\Repos\arkade5\src\Arkivverket.Arkade.UI\ViewModels\TestRunnerViewModel.cs:linje 241

---------------------------
OK   
---------------------------

Problemet er at datatypene som er tillatt er 
            switch (dataType.ToLower())
            {

                case "string":
                    return new StringDataType(format, nullValues);
                case "integer":
                    return new IntegerDataType(format, nullValues);
                case "float":
                    return new FloatDataType(format, nullValues);
                case "date":
                    return new DateDataType(format, nullValues);
                case "boolean":
                    return new BooleanDataType(format, nullValues);
                case "link":
                    return new LinkDataType();
                default:
                    throw new AddmlDefinitionParseException("Unknown datatype " + fieldType.dataType);
            }
(Arkivverket.Arkade/Core/Addml/Definitions/AddmlDefinitionParser.cs, ln 95-112)

For dateTime[/datetime/DateTime..] og time, legg til to datatyper som bruker datetime, og ignorer date-biten i datatypen time..

AV/Jørgen

**Comment by erikaaberg** [comment]
Antas løst.

**Comment by joafug** [comment]
Løst
