### ISSUE TITLE
Koden lar seg ikke bygge med Visual Studio på MacOSX

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/arkade5#36]
Jeg fikk en kamerat til å forsøkte å bygge denne koden på MacOSX, og han melder om følgende problem:

> Arkade koden vil ikke la seg åpne i Visual Studio på mac. Så jeg har dratt ut importerte biblioteker av koden og så forsøkt finne alle som kodeanalyseren ikke gjenkjenner på NuGet (et bibliotek repository). Om den hadde funnet alle (eller nesten alle), ville neste steg vært å legge inn koden med c´n´p, og så lett etter versjonsavhengigheter (igjen brukt en syntaks-analyzer). Om det da hadde gjenstått mindre mangler kunne man forsøkt skrive om denne koden. 

Det virker dermed som om det ikke er så enkelt å flytte programmet over på andre aktuelle platformer, slik https://www.mimesbronn.no/request/informasjon_om_operativsystemkra forteller lå inne i kravspesifikasjonen:

> "Det som utvikles skal enkelt kunne installeres og kjøres på en standard Windows-installasjon uten krav til ekstra programvare. Det bør også være enkelt å flytte all programvare til andre aktuelle operativsystemer. Riksarkivets foretrukne plattformer er Windows og MAC på klientsiden, og Linux på server siden."

Kan dere endre koden slik at den bygger på MacOSX?

Dette er relatert til utfordring #16 og #10.

**Comment by erikaaberg** [comment]
For å ta det siste først. Nei - vi kan ikke endre koden **nå** slik at den bygger på Mac.

Så til "bør også være enkelt". **bør** . Spesifikasjonen inneholder et antall krav (der de fleste er **må**). I den virkelige verden hvor vi må forholde oss til tid og budsjetter fikk vi dessverre ikke med alle "bør" krav. Valg av løsning og leverandør ble gjort etter en omfattende vurdering pro/contra. Og da måtte vi være såpass pragmatiske at vi **prioriterte brukerbehov**. I samtlige aktuelle statlige etater sitter nok de arkivansvarlige på en Windows plattform. Det samme ser ut til å gjelde innen kommunal sektor. For privat sektor har vi ikke eksakte tall, men generelt er mer enn 90 prosent av klienter Windows basert (statistikk februar 2017, mobile klienter unntatt). IT-avdelinger og konsulenter vil ofte foretrekke Linux eller Mac, men også de vil vanligvis ha tilgang på en Windows maskin.

Når det er sagt: Det ser ut som dere har gjort et godt stykke arbeid med å identifiserer problemer ved en eventuell porting til andre plattformer. Det kan vise seg nyttig ved fremtidig utvikling, men vi har ikke mulighet til å gå i detalj på det **nå**. Det mest aktuelle her er antagelig å splitte applikasjon i klient/tjener - og eventuelt kjøre tjeneren på annet OS - f.x. Linux. Da vil også en web versjon kunne implementeres - som ytterligere senker terskelen for bruk.

**Comment by petterreinholdtsen** [comment]
Tusen takk for svaret.  Det var nyttig å få innsikt i hvordan dere ser på problemstillingen.

Du nevner en statistikk over operativsystemfordeling for klienter i bruk i Norge som jeg ikke kjenner.  Kan du fortelle hvor jeg kan finne den?  Er interessert i å se om den forteller litt om hvordan operativsystemfordelingen endrer seg over tid.

**Comment by erikaaberg** [comment]
Statistikk jeg refererte til er todelt. Når det gjelder arkivskapere/ansvarlige i **Norge** baserer det seg på informasjonsutveksling med folk som har oversikten innen statlig og kommunal sektor. Når det gjelder **generell** OS statistikk gjorde jeg det litt enklere - ved rett og slett å lete etter statistikk via Google. Og brukte da denne: https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0. NB: Den er ikke spesifikt norsk.

**Comment by joafug** [comment]
Det er laget en kommandolinje-versjon:
[(http://arkade.arkivverket.no/no/latest/Systemdokumentasjon.html#arkade-api)]

GUI blir ikke prioritert nå.

Det er laget veiledning for tilpasning til andre plattformer:
[(http://arkade.arkivverket.no/no/latest/Systemdokumentasjon.html#porting-to-other-platforms)]
