### ISSUE TITLE
Innlesing av .tar som ikke Er en SIP pakke. 

### ISSUE THREAD

**Issue by erikaaberg** [arkivverket/arkade5#37]
Programmet forventer nå at en .tar som leses inn har SIP struktur. Det må også kunne leses inn 

   1: en vanlig (OS) mappestruktur pakket som .tar (viktig)
   2: en AIP (litt forskjellig fra SIP) pakket som .tar (ikke så viktig nå)

Begge deler er en utvidelse av spec., men vi regner med å få inn punkt 1 i første versjon.
2 settes som ønske til neste versjon.

**Comment by solfeggietto** [comment]
Inkluderer punkt 1. at f. eks. "dokumenter\dokumenter.tar" vil forstås av Arkade 5 som denne tar-fila var pakket ut i mappa dokumenter?

Poeng: 
Noark 5 uttrekksformat har sjekksom av alle dokumentfiler som metadata i  noark 5 xml uttrekks-metadata allerede. Derfor vil det ikke være noen grunn til at DIAS SIP (eller AIP og AIC) skal ha med doble sett av sjekksummer, både i selve Noark 5-uttrekket selv i tillegg til at METS og PREMIS og ev LOGG-filer i DIAS SIP strukturen skal liste opp og ha sjekksummer til disse samme filene. Fordi IP-pakkestrukturen er på et annet "lag" enn innholdet (Noark 5-uttrekket).

**Comment by joafug** [comment]
Ligger allerede en sak i gjøremålslisten for:
1: en vanlig (OS) mappestruktur pakket som .tar (viktig)
2: en AIP (litt forskjellig fra SIP) pakket som .tar (ikke så viktig nå)

Ref: Arkade-70

@solfeggietto 
Deling av data og dokumenter kan bli en utfordring. Vi har lagt dette inn som en sak på gjøremålslisten. Tror ikke vi får prioritert dette opp i Arkade-prosjektet i første omgang. Vi prioriterer det om vi får anledning.

Ref: Arkade-201
