### ISSUE TITLE
Sjekk av Noark4 - Observasjoner

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#4]
![skjermdump](https://cloud.githubusercontent.com/assets/1849298/22292370/20439850-e30b-11e6-94dc-70999a17c4c7.jpg)
![skjermdump2](https://cloud.githubusercontent.com/assets/1849298/22292410/59d47f76-e30b-11e6-8bc7-b3abbd1edc12.jpg)

Når jeg sjekker et noark4-uttrekk i .tar format forventer den at NOARKIH.XML ligger i content-mappa. Hvis jeg velger samme uttrekket med "Velg katalog" og velger mappa for noark4-uttrekket forventer den å finne NOARKIH.XML i rotmappa. Stemmer dette?

Ser også at når jeg er ferdig med en kjøring av en mappe, får jeg spørsmål om å lage pakke. Pakke genereres, men <uuid>.tar-fila havner i rot-mappe, og ikke i /content-mappa. Den burde vel havne der såvidt jeg kan skjønne.

Statusteksten om at pakken er lagret, og listing av mappenavnet, etter endt laging av pakke er også "trødd" sammen i et veldig smalt felt til venstre i skjermbildet under knappene nederst i vinduet. Bør utvidet, så det blir litt mer lesbart.

**Comment by erikaaberg** [comment]
ENIG her også. Relaterer også til issue #3 - om fil lokasjoner. Lukker denne - den er nå listet under forbedrringer. "Statustekst" tas over i ny issue.
