### ISSUE TITLE
Test av feltverdier i flate filer

### ISSUE THREAD

**Issue by PetterBAR** [arkivverket/arkade5#43]
Når et felt (boolsk i dette tilfellet) ikke er obligatorisk og mangler verdi (som da er lov), rapporterer allikevel Control_DataFormat om ugyldig dataformat. I det medfølgende eksemplet har datafilen fast format og den tomme verdien er et space for å fylle ut posten.

Jeg har lagt ved relevante filer som txt siden GitHub ikke lot meg dra alt mulig rart inn hit.

[arkivuttrekk.xml.txt](https://github.com/arkivverket/arkade5/files/855305/arkivuttrekk.xml.txt)
[FIL1.DAT.txt](https://github.com/arkivverket/arkade5/files/855306/FIL1.DAT.txt)
[report.html.txt](https://github.com/arkivverket/arkade5/files/855339/report.html.txt)

**Comment by joafug** [comment]
Feil som må rettes.

Lagt inn i gjøremålsliste

Ref: Arkade-202

**Comment by joergen-vs** [comment]
Dette er ikke gyldig addml, siden 'Boolean1' teknisk sett blir en string med enumeration for "1", "0" og "", med padChar = " ".
Og posten mangler et mellomrom for å få korrekt lengde, siden det er fastlengde-post.

**Comment by PetterBAR** [comment]
Jeg er ikke helt enig i det Jørgen skriver.
Posten det er snakk om, er paddet med et mellomrom, noe som gjør at alle poster i aktuell datafil har fast lengde. Jeg mener også fra tidligere, så var standard paddetegn mellomrom, noe som ikke gjorde det obligatorisk å angi dette tegnet (padchar). Siden det boolske feltet ikke er obligatorisk, er det nødvendig med et mellomrom (som er der) for å fylle ut posten når det ikke er angitt true/false (1/0). Angivelsen av det boolske datatypen, tillater derfor 1 for true, 0 for false og mellomrom for ikke oppgitt. En uttalelse fra Terje her er kanskje lurt for å avgjøre hva som er obligatorisk og "riktig"? For eksempel om det skal være obligatorisk med padchar under fieldType når det er fast format. Jeg må innrømme at jeg ikke har sjekket beskrivelsen av den norske bruken av ADDML 8.2/8.3.

**Comment by joergen-vs** [comment]
Ikke begrenset til addml, må en bolsk verdi ha en av to verdier, sann eller usann.
Angivelse av ikke-obligatorisk bolsk verdi betinger ikke at man kan lese verdien sann, usann eller ikke oppgitt. Det betinger at verdien til et bolsk felt vil alltid være sann eller usann. Men i egnede strukturer vil det være selve feltet som ikke er obligatorisk,  og dermed ikke være del av enkelte poster, som gir verdien "ikke oppgitt" når posten leses.
Fastlengde er ikke egnet til dette, da et felt alltid vil være tilstede. Tilsvarende for tegnseparert, feltet vil forekomme tomt, med feltskille foran og bak /  eller postskille bak. Xml eller tilsvarende avanserte strukturer muliggjør å fullstendig utelukke feltet fra en post.

Kan være enig i det med padChar,  burde være definert høyere [fil-/postnivå].
