### ISSUE TITLE
Hull i saksnr. rekkefølge

### ISSUE THREAD

**Issue by erikaaberg** [arkivverket/arkade5#48]
Ønsker sjekk/rapport på dette. Generelt: Noark 4 tester som gjøres i Arkn4, men ikke Arkade 5 bør implementeres.

**Comment by SteinarAbrahamsen** [comment]
Hvordan kan en test for hull i saksnummer når det er mulig å avlevere data fra en (av flere) arkivdeler?

**Comment by erikaaberg** [comment]
Vi ser på det. Men innen en arkivdel skal det vel ikke være (for) store hull.

**Comment by MonaHen** [comment]
Det kan være store hull på saksnummer i en arkivdel Erik. Fredrikstad kommune begynner å få ganske mange arkivdeler (noen hyppigere brukt enn andre), saksnummer tildeles ikke per arkivdel. Det vil ikke gjøres uttrekk fra alle arkivdelene samtidig.

**Comment by erikaaberg** [comment]
Du har visst aldeles rett. Vi kommer tilbake til saken.

**Comment by joafug** [comment]
Lagt inn i gjøremålsliste.
Dette kan være vanskelig å løse.
Ikke prioritert nå.

Ref: Arkade-203
