### ISSUE TITLE
Noark3-test - Usikker på hva som kan testes her?

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#5]
Prøvde meg på et Noark3-uttrekk, og prosesssen starter, og stopper igjen med følgende skjermbilde:
![skjermdump2](https://cloud.githubusercontent.com/assets/1849298/22364120/5ed91850-e46f-11e6-8718-03260c8f2114.jpg)

Skal det skje noe mere? Regner ikke med noark3 er fokusområde akkurat, men hadde vært kjekt med en litt mer fornuftig tilbakemelding, og mulighet til å kjøre "Ny kjøring" i det minste, uten å måtte lukke ned programmet.

Antar det mangeler noe funksjonalitet rundt dette for øyeblikket..

**Comment by erikaaberg** [comment]
N-3 tester ser nå ut til å virke bra.
