### ISSUE TITLE
Noark-4 - Feil datoformat i addml.xml

### ISSUE THREAD

**Issue by PetterBAR** [arkivverket/arkade5#52]
Arkade 5 - versjon 0.6.18.0

I Noark 4.1 er formatet til datoer i uttrekk definert i 14.1.1 (kanskje andre steder også?).
Datoer skal være på formen YYYYMMDD, mens det i den genererte addml.xml er definert med ddmmyyyy (date8).
Det siste genererer feilaktig mange feil for SA.DATO som det er lagt dataformatkontroll på.

**Comment by PetterBAR** [comment]
Er dette tenkt fikset før endelig versjon av Arkade 5 (release 1.0)?
Det er transformasjonen fra NOARKIH.XML til addm.xml som må endres.

**Comment by PetterBAR** [comment]
Denne ser ut til å være fikset?

**Comment by joafug** [comment]
Løst
