### ISSUE TITLE
Årstall-lister kan gjerne være sortert kronologisk

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#56]
![clipboard01](https://cloud.githubusercontent.com/assets/1849298/24799310/cf28d4d0-1b9a-11e7-9991-856401792845.jpg)

Listere med årstall i rapporten kan gjerne være sortert kronologisk for bedre lesbarhet.
Gir lite mening å presentere dem slik de står nå.

**Comment by joafug** [comment]
Dette må forbedres
Lagt inn i gjøremålsliste.
Ref: Arkade-206
