### ISSUE TITLE
DIAS SIP elementer, struktur og kompabilitet

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#57]
DIAS IP-struktur er definert pr. DIAS sluttrapport 2012 og implementert av ESSArch Tools for Producer (ETP), ESSArch Tools for Archivist (ATA) og ESSarch Preservation Platform (EPP), basert på samme elementer som i Arkade 5 spesifikasjon: "info.xsd", "Info_xml.doc" derunder "eksemlep-mets-info.xml".

1. ESSArch bruker mets.xsd som basis for info.xml

1.a Komplett sett agenter iht. "Info_xml.doc" må implementeres og beste praksis for utfylling av agentinfo MÅ være fornuftig, dekkende og ha gode titler og hjelpetekster.

1.b En plan for samkjøring med- og migrering over til korrekt agentformat må gjøres mot ESSArch. Arkade 5 skal erstatte ETP mht å lage DIAS SIP. Derfor må man ha full kontroll på hvilke elementer som finnes (inkl. feil) i eksisterende DIAS SIP/AIP/AIC fra ETP/ETA/EPP slik at innføring av nytt verktøy Arkade 5 med det fulle settet av agent-elementer i info.xml (og videre inn i METS og PREMIS log.xml, mets.xml og premis.xml i DIAS SIP/AIP/AIC). Langtidsforvaltning i depot krever dette!

Forklaring:
Med elementene som beskrevet i "Info_xml.doc", bare at ESSArch kun støtter de elementer som eksempelfila her angir og ikke det fulle sett med elementer. Samt tar med de 2 feil som er i eksempelet, der <agent: ROLE="ARCHIVIST" TYPE="OTHER" OTHERTYPE="SOFTWARE"><name> er i 3 identiske seksjoner. Det korrekte er at de 2 siste skulle vært <note> element. Bruken av agenter i eksmpelet treffer ikke helt på noen av elementene, blant annet de 2 nevnte over bla fordi det totale settet agenter iht. "Info_xml.doc" da ikke er implementert i ESSArch og feltbeskrivelsen i webgrensesnitt for utfylling er litt misvisende. 

Arkade 5 dokumentasjon "Info_xml.doc" har fått rettet de 2 nevnte elementer til <note>, men eksempelet i dokumentasjonen har fortsatt <name> der. Vedlagt "Info_xml.doc_med-merknader.pdf" er opprionnelig versjon fra 2013 med feil og blyantnotater og feltgjennomgang skriblet på.

Vedlagt en full test av alle elementer i ETP/ETA/EPP av elarkivdb demo under inklusiv alle SIP/AIP/AIC med alle elementer pakket i .tar og utpakket på alle nivå under. Derunder i regneark opplisting av alle felter (agenter) og annet som eksisterer på ulike nivåer og elementer.

[2016-12-20 ET EPP Test.zip](https://github.com/arkivverket/arkade5/files/947071/2016-12-20.ET.EPP.Test.zip)

[Info_xml.doc_med-merknader.pdf](https://github.com/arkivverket/arkade5/files/947122/Info_xml.doc_med-merknader.pdf)

[info.xsd_2016-08-18.xml.txt](https://github.com/arkivverket/arkade5/files/947127/info.xsd_2016-08-18.xml.txt)

**Comment by erikaaberg** [comment]
Gjennomgås for senere dokumentasjon - og evt. oppfølging i kode.

**Comment by erikaaberg** [comment]
Test av ESSArch kompatibilitet (inkl. noen "besvergelser" etter at Arkade har laget en pakke) har vist seg vellykket.
