### ISSUE TITLE
Rapportering av antall feil av samme type

### ISSUE THREAD

**Issue by palm72** [arkivverket/arkade5#59]
Testrapporten viser i dag et begrenset antall linjer med feil av samme type. Dette er OK for å slippe mye likelydende feil. Det kunne imidlertid vært svært nyttig å se hvor mange ganger samme feil dukker opp i uttrekket. 
Et eksempel: Ved test av "Antall ulike journalposttyper"  får jeg opp en liste over journalposter som mangler hoveddokument. Dokumentene er registrert som vedlegg, så feilen er korrekt. Jeg vet imidlertid ikke hvor mange slike feil som finnes i uttrekket.

**Comment by erikaaberg** [comment]
Dette er nå løst for noen feil - men muligens ikke generelt - ennå.

**Comment by erikaaberg** [comment]
Forbedret. Skal nå virke generelt.
