### ISSUE TITLE
Tegnseparert format - Siste post blir ikke behandlet når postskille mangler

### ISSUE THREAD

**Issue by PetterBAR** [arkivverket/arkade5#60]
Arkade 5 versjon 0.6.24
Ved behandling av tegnseparerte filer blir ikke siste post lest når postskille mangler.
Det er vel tillatt å utelate postskille etter siste post, så da skulle den siste posten også ha vært lest.

[addml.xml.txt](https://github.com/arkivverket/arkade5/files/973470/addml.xml.txt)
[klient.dat.txt](https://github.com/arkivverket/arkade5/files/973471/klient.dat.txt)

**Comment by erikaaberg** [comment]
Er under behandling. Ref. også relatert feil - dersom postskiller mangler (midt i) så terminerer programmet.

**Comment by erikaaberg** [comment]
Løst
