### ISSUE TITLE
Tegnseparert format - stopp med to typer poster

### ISSUE THREAD

**Issue by PetterBAR** [arkivverket/arkade5#61]
Arkade 5 versjon 0.6.24.0

En datafil med to typer poster. Primærnøkler og en fremmednøkkel. 
Tegnseparert format uten omslutningstegn. Ingen prosesser angitt eksplisitt.

Kjøringen stopper med "System.NullReferenceException: Objektreferanse er ikke satt til en objektforekomst.
ved Arkivverket.Arkade.Core.Addml.DelimiterFileFormatReader.GetCurrentRecord()".

[stack_trace.txt](https://github.com/arkivverket/arkade5/files/975803/stack_trace.txt)
[addml.xml.txt](https://github.com/arkivverket/arkade5/files/975804/addml.xml.txt)
[klientinfo.dat.txt](https://github.com/arkivverket/arkade5/files/975805/klientinfo.dat.txt)
![skjermbilde](https://cloud.githubusercontent.com/assets/21096792/25699519/e2555ab8-30c3-11e7-9e71-fe9790f3421f.PNG)

**Comment by JanGravArkivTroms** [comment]
Samme feil for Arkade 5 v1.2.1.0.
Errorlog:
System information:
Arkade version: 1.2.1.0
.NET CLR: 4.0.30319.42000
Total disk space: 235769163776 (224846 MB)
Available disk space: 68616794112 (65438 MB)

Stack trace:
System.NullReferenceException: Objektreferanse er ikke satt til en objektforekomst.
   ved Arkivverket.Arkade.Tests.Noark5.NumberOfEachDocumentStatus.GetTestResults()
   ved Arkivverket.Arkade.Core.Noark5.Noark5BaseTest.GetTestRun()
   ved Arkivverket.Arkade.Core.Noark5.Noark5TestEngine.AddTestToTestSuite(IEnumerable`1 tests, TestSuite testSuite)
   ved Arkivverket.Arkade.Core.Noark5.Noark5TestEngine.RunTestsOnArchive(TestSession testSession)
   ved Arkivverket.Arkade.Core.ArkadeApi.RunTests(TestSession testSession)
   ved Arkivverket.Arkade.UI.ViewModels.TestRunnerViewModel.RunTests() i C:\dev\TeamCity\buildAgent\work\bc41c1d9527376de\src\Arkivverket.Arkade.UI\ViewModels\TestRunnerViewModel.cs:linje 284

**Comment by joergen-vs** [comment]
Er dette testdata, som du er villig til å dele? Sliter med å reprodusere feilen.
Alternativt må du gå gjennom dokumentbeskrivelse.dokumentstatus for å se om den mangler noen steder..

**Comment by PetterBAR** [comment]
De filene jeg opprinnelig brukte (addml- og datafil), ligger på issue'en. Går en kjøring med dem bra? Jeg har ikke fått testet selv ennå.

**Comment by joergen-vs** [comment]
@PetterBAR: Arkade støtter fremdeles bare en posttype per fil (ironisk, siden Noark 5). Etter at Noark 5-testing er på plass, vil dette prioriteres.
@JanGravArkivTroms: Den opprinnelige feilen gjaldt fagsystem, ikke Noark 5. Min kommentar over gjelder arkivstruktur.xml

**Comment by PetterBAR** [comment]
Hva med testing av Noark-3-uttrekk? DOK.DAT inneholder to posttyper og er i addml.xml definert som et fagsystem med to posttyper i den datafilen, samt relasjoner fra postene i DOK.DAT til SAK.DAT.

**Comment by joergen-vs** [comment]
Enhver fil med mer enn én posttype vil idag få Arkade5 til å feile. Dette er rapportert, og vil løses, etter Noark5 er på plass.

N3:
Saksregister
	Saksregisterpost
Dokumentregister
	Eksterne_dokumenter
	Interne_dokumenter << Arkade vil feile
Arkivnoekkelregister
	Arkivnoekkelregisterpost

**Comment by JanGravArkivTroms** [comment]
Jeg fikk feilen under testing av en NOARK 5-avlevering. Nå hørte jeg på KDRS-samlinga igår at ny (og nærmest umiddelbart tilgjengelig :-) ) versjon av ARKADE gir bedre feilmeldinger, så jeg tester igjen når ny versjon foreligger.

**Comment by JanGravArkivTroms** [comment]
Én mulig måte å spore slike feil, er at Arkade sier mer enn den litt intetsigende statusen "Antall xml-elementer prosessert: ..." - f.eks "Prosesserer <filnavn>.xml linje <linjenr>".

**Comment by PetterBAR** [comment]
Har det skjedd noe med denne?

Hvis ikke, er det ikke mulig å teste Noark-3-uttrekk.
Så da bør muligens Noark-3-valget i brukergrensesnittet også disables?

**Comment by erikaaberg** [comment]
Kommentar: 2 ting her.

1: Noark 3 **kan** testes. Det har vært et problem når feltseparator ikke har vært anførselsteng. Det er nå løst. 

2: "Ingen prosesser angitt eksplisitt." Det er i utgangspunktet ikke mulig å definere prosesser i ADDML-en per fil. Dette må vi leve med.
