### ISSUE TITLE
DTD'er: Finnes i arkiv, men ikke i ADDML 

### ISSUE THREAD

**Issue by rholte** [arkivverket/arkade5#68]
TESTET N4 uttrekk i versjon 0.641.0 (Arkade versjonnr burde også stå i report.html??)

Alle DTD kommer opp som ikke definert i ADDML disse burde vært listet som feil
Muligens også ikke INFO.TXT og INNHOLD.TXT

INFO.TXT  Finnes i arkiv, men ikke i ADDML  
INNHOLD.TXT  Finnes i arkiv, men ikke i ADDML  

NOARKIH.DTD  Finnes i arkiv, men ikke i ADDML  
DATA\ADMINDEL.DTD  Finnes i arkiv, men ikke i ADDML  
...
DATA\UTVBEHDO.DTD  Finnes i arkiv, men ikke i ADDML  
DATA\UTVMDOK.DTD  Finnes i arkiv, men ikke i ADDML  
DATA\UTVMEDL.DTD  Finnes i arkiv, men ikke i ADDML  
DATA\UTVMOTE.DTD  Finnes i arkiv, men ikke i ADDML  

Dette er påkrevde (rapport)filer med tilhørende dtd
RAPPORT\JOURNAL.DTD  Finnes i arkiv, men ikke i ADDML  
RAPPORT\JOURNAL.XML  Finnes i arkiv, men ikke i ADDML  
RAPPORT\SAKDOK.DTD  Finnes i arkiv, men ikke i ADDML  
RAPPORT\SAKDOK.XML  Finnes i arkiv, men ikke i ADDML

**Comment by erikaaberg** [comment]
Dette vil bli fixa.

**Comment by PetterBAR** [comment]
Samme feilmelding kommer for hver dokumentfil også.

**Comment by erikaaberg** [comment]
Ikke lenger relevant. Arkade tester ikke Noark-4. Det ble for mye arbeid i forhold til behov.
