### ISSUE TITLE
Manglende sjekk på fremmednøkler

### ISSUE THREAD

**Issue by erikaaberg** [arkivverket/arkade5#69]
Gjelder Noark-4.

Er under utbedring/retting.

**Comment by PetterBAR** [comment]
Det er definert en fremmednøkkel i generert addml.xml i en Noark-4-kjøring på relasjonen mellom NOARKSAK (SA.UTLTIL) og PERNAVN (PN.ID).
Arkade 5 kommer med en feilmelding: "Missing ADDML definition object for field: noarksak/noarksak/sa.utltil". 
Dette er vel egentlig ikke en feil siden SA.UTLTIL står i kursiv i standarden, noe som betyr at feltet ikke skal inngå i uttrekk.
Samme type feilmelding forekommer for flere tabeller/felt, men jeg har ikke hatt tid til å ettergå dem.
Så vidt jeg kan se, vil en kjøring på et reelt uttrekk avdekke disse situasjonene.

**Comment by erikaaberg** [comment]
Ikke lenger relevant. Arkade fikk aldri helt til å teste Noark-4 skikkelig.
