### ISSUE TITLE
Feiler på filreferanser

### ISSUE THREAD

**Issue by palm72** [arkivverket/arkade5#7]
Jeg benytter Arkade5 versjon 0.5.7.0 og tester et Noark-4 uttrekk. Her mottar jeg mange feilmeldinger om at dokumentfiler "Finnes i arkiv, men ikke i ADDML". Filene er imidlertid definert i DOKVERS.XML med sti relativ til DOKUMENTER.

Feilmelding:
Lokasjon: DOKUMENT\DOK001\1.PDF
Melding: Finnes i arkiv, men ikke i ADDML

fra DOKVERS.XML:
<VE.FILREF>\DOK001\1.PDF</VE.FILREF>

Dette var gjennomgående for dette uttrekket. Filreferansene er relative til den pålagte plasseringen .\DOKUMENT\

Testen bør håndtere dokumenthenvisninger som henviser til plassering ./DOKUMENT/ og ./ i forhold til roten av uttrekket.

**Comment by joafug** [comment]
Fikset i senere versjon
