### ISSUE TITLE
Problemer ved bruk av " i CSV-filer

### ISSUE THREAD

**Issue by nikolaia** [arkivverket/arkade5#77]
Hei,

Håper det går greit at jeg åpner et Issue her, men virker som korteste veien til å få et svar. Sliter med at Arkade 5 (v. 0.7.0.0) ikke støtter `"` brukt i CSV-filer. Det skaper en del problemer når det er fritekstfelt som arkiveres (hvor alle tegn kan forekomme) og det ikke er ønskelig å gjøre uttrekkene om til XML.

På en linje som denne vil det rapporteres feil om for mange felt:
```
kolonne1;kolonne2;kolonne3
abc;";ames Bond";abc
```
Følgende CSV-linje gir tre feil om for få felter:
```
kolonne1;kolonne2;kolonne3
abc;";ames

Bond";abc
```
Om jeg base64-encoder feltene går de fint igjennom, men feltet kan da kun leses av maskiner og der av ikke like gunstig for arkivering.

**Comment by erikaaberg** [comment]
Takk for at du tester. Dette er en generell feil. Dersom feltskiller forekommer inne i en streng (omgitt av anførselstegn) så feiler det. Derav feilmeldingen i ditt første eksempel. Ditt andre eksemperl _er_ faktisk feil - da strengen ikke er avsluttet. Det mangler et anførselstegn. Men du hadde jo ikke behøvd _3_ feilmedlinger.

Men feilen er faktis registrert tidligere (no. 72 -https://github.com/arkivverket/arkade5/issues/72) - så jeg lukker denne. Vi retter i feilen om ikke lenge.

Angående "korteste veien til å få et svar". Prøv gjerne å sende mail direkte til meg - Erik Aaberg - eriaab@arkivverket.no.
