### ISSUE TITLE
Metadatakatalog-versjon - tilknyttetDato-format?

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#78]
Har et spørsmål om hva som er riktig format på feltet tilknyttetDato i Metadatakatalogen (M620)

Står i Noark5-standarden at det er type Date, men i diverse revisjoner og nettsiden er dette endret til DateTime. 
Data jeg får fra uttrekksleverandør er i DateTime, mens Arkade5 krever Date.

Hva er riktig, og hvilken versjon av Metadatakatalogen benytter Arkade5 seg av i såfall? (pre v3?)

**Comment by joafug** [comment]
Hei @smult
Godt spørsmål. Har sjekket opp litt og m620 xs:date ble endret til xs:dateTime i versjon 3.1. Endringen ble den gang listet som en rettelse.

Har forsøkt å gjenskape feilen, men har ikke lyktes. Arkade5 bruker i utgangspunktet den metadatakatalog.xsd som ligger i Noark5-uttreksmappen. Om det ikke følger med en mtadatakatalog.xsd faller Arkade5 tilbake på inebygget metadatakatalog.xsd, den er akkurat nå v3.1. 

Har testet og den innebygde slår ut når jeg bare bruker Date i tilknyttetDato i dokumentbeskrivelse. Har du et eksempel?

**Comment by joafug** [comment]
Ved bruk av innebygget metadata.xsd vises følgende feilmelding:

(addml.xml er ikke gyldig i henhold til XML-skjema: Elementet http://www.arkivverket.no/standarder/noark5/arkivstruktur:tilknyttetDato er ugyldig - Verdien 1864-05-04 er ugyldig i henhold til datatypen http://www.arkivverket.no/standarder/noark5/metadatakatalog:tilknyttetDato - Strengen 1864-05-04 er ikke en gyldig DateTime verdi.

Skjemafil metadatakatalog.xsd ble ikke funnet i uttrekket. Validering gjøres ihht. en versjon av metadatakatalog.xsd som er innebygget i Arkade

arkivstruktur.xml er ikke gyldig i henhold til XML-skjema: Elementet http://www.arkivverket.no/standarder/noark5/arkivstruktur:tilknyttetDato er ugyldig - Verdien 1864-05-04 er ugyldig i henhold til datatypen http://www.arkivverket.no/standarder/noark5/metadatakatalog:tilknyttetDato - Strengen 1864-05-04 er ikke en gyldig DateTime verdi.

arkivstruktur.xml er ikke gyldig i henhold til XML-skjema: Elementet http://www.arkivverket.no/standarder/noark5/arkivstruktur:tilknyttetDato er ugyldig - Verdien 1864-05-04 er ugyldig i henhold til datatypen http://www.arkivverket.no/standarder/noark5/metadatakatalog:tilknyttetDato - Strengen 1864-05-04 er ikke en gyldig DateTime verdi.)

**Comment by smult** [comment]
Dette er et Noark5-uttrekk fra en ephorte-base.
Arkade gir meg følgende (legger ved 2 feilmeldinger av flere tusen..):

addml.xml er ikke gyldig i henhold til XML-skjema: Elementet http://www.arkivverket.no/standarder/noark5/arkivstruktur:tilknyttetDato er ugyldig - Verdien 2005-11-22T10:49:00 er ugyldig i henhold til datatypen http://www.arkivverket.no/standarder/noark5/metadatakatalog:tilknyttetDato - Strengen 2005-11-22T10:49:00 er ikke en gyldig Date verdi.

addml.xml er ikke gyldig i henhold til XML-skjema: Elementet http://www.arkivverket.no/standarder/noark5/arkivstruktur:tilknyttetDato er ugyldig - Verdien 2005-10-19T13:12:00 er ugyldig i henhold til datatypen http://www.arkivverket.no/standarder/noark5/metadatakatalog:tilknyttetDato - Strengen 2005-10-19T13:12:00 er ikke en gyldig Date verdi.

Jeg får altså "er ikke en gyldig Date verdi" og ikke "er ikke en gyldig DateTime verdi" som deg. 
Jeg har siste versjon av Arkade5 (v1.0.4.0)

Jeg har altså en gyldig DateTime, men arkade forventer en Date.

Benytter Arkade5 seg av metadatakatalog.xsd fra arkivpakka? Eller har den sin egen?

**Comment by smult** [comment]
arkivstruktur.xsd i pakka har linja <xs:element name="tilknyttetDato" type="n5mdk:tilknyttetDato" />

metadatakatalog.xsd i pakka har linjene:
  <xs:simpleType name="tilknyttetDato">
    <xs:annotation>
      <xs:documentation>M620</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:dateTime"/>
  </xs:simpleType>

Så her burde datoformatet være korrekt.

**Comment by erikaaberg** [comment]
Formatet skal være Datetime. Saken lukkes.
