### ISSUE TITLE
Feil i arkivstruktur.xml

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#79]
Får mange av følgende i et Noark5-uttrekk:

arkivstruktur.xml er ikke gyldig i henhold til XML-skjema: Elementet dokumentobjekt i navneområdet http://www.arkivverket.no/standarder/noark5/arkivstruktur har ugyldig underordnet element filstoerrelse i navneområdet http://www.arkivverket.no/standarder/noark5/arkivstruktur. Forventet liste over mulige elementer: sjekksum i navneområdet http://www.arkivverket.no/standarder/noark5/arkivstruktur.

arkivstruktur.xml er ikke gyldig i henhold til XML-skjema: Elementet dokumentobjekt i navneområdet http://www.arkivverket.no/standarder/noark5/arkivstruktur har ugyldig underordnet element filstoerrelse i navneområdet http://www.arkivverket.no/standarder/noark5/arkivstruktur. Forventet liste over mulige elementer: sjekksum i navneområdet http://www.arkivverket.no/standarder/noark5/arkivstruktur.

arkivstruktur.xml er ikke gyldig i henhold til XML-skjema: Elementet klasse i navneområdet http://www.arkivverket.no/standarder/noark5/arkivstruktur har ugyldig underordnet element opprettetDato i navneområdet http://www.arkivverket.no/standarder/noark5/arkivstruktur. Forventet liste over mulige elementer: tittel i navneområdet http://www.arkivverket.no/standarder/noark5/arkivstruktur.

Ser ikke for meg ut til at det er feil i arkivstruktur.xsd som ligger med uttrekket, og skjønner ikke hvorfor den kun maser etter filstoerrelse?

Se vedlagt skjermdump med forklaring.

![image](https://user-images.githubusercontent.com/1849298/34149319-fe56b712-e4a4-11e7-8b4c-418e48a2197b.png)

Hadde også være knaganes kjekt med ett anslått linjenummer på feilen i XML-fila, så jeg hadde noe å gå etter når jeg skal forsøke å finne igjen hvor i fila den feiler...

**Comment by PetterBAR** [comment]
Hei!

Det ser ut til at det obligatoriske elementet sjekksum mangler i de aktuelle forekomstene av dokumentobjekt og at dette er det første obligatoriske elementet som mangler. Parseren vil da ikke melde fra om eventuelle andre obligatoriske elementer som mangler. Det vil si at hvis elementet sjekksumAlgoritme mangler, vil en ikke få beskjed om det før elementet sjekksum får en verdi. Elementet filstoerrelse er tilfeldigvis det første elementet som forekommer etter det obligatoriske elementet referanseDokumentfil.

Hilsen
Petter

**Comment by erikaaberg** [comment]
Her får vi dessverre ikke gjort noe mer foeløpig med validatoren.
