### ISSUE TITLE
Plassering av nyopprettet pakke

### ISSUE THREAD

**Issue by palm72** [arkivverket/arkade5#8]
Når jeg benytter Arkade5 v 0.5.7.0 for å opprette en ny SIP fra et Noark-4 uttrekk blir pakken plassert i %USERPROFILE%\Arkade\Work.
Det bør være mulig å velge plassering for denne lagringen.

**Comment by erikaaberg** [comment]
Overføres som ønske til neste versjon.

**Comment by rholte** [comment]
Stusser også litt på navnesetting av katalog under work. Hvorfor er dato en del av stien og ikke bare UUID rett under work katalog. Om dato er så viktig burde heller man splitte dato og UUID. Forøvrig om  man vet hviken type UUID som lages kan denne gi mer info: 

versjon 1 lages av MAC og dato. 
versjon 2 lages av date-time, MAC Address, DCE security version. https://en.wikipedia.org/wiki/Universally_unique_identifier. 

Dette betyr om man bruker UUID v1 eller v2 kan man dekode tid og lokasjon denne er lagd. (MAC addresse og tidspunkt). 

ref: C:\Users\rolhol\Arkade\work\20170529144708-f6f71c91-40e8-4b57-8642-1ce977b4c27f\

**Comment by joafug** [comment]
Dette er fikset. Det er nå mulig å velge hvor SIP skal lagres.
