### ISSUE TITLE
Noark-4 - Variasjon i navngiving gir feil under testkjøring

### ISSUE THREAD

**Issue by PetterBAR** [arkivverket/arkade5#80]
Arkade 1.0.5.90
I det Noark-4-uttrekket jeg skal kjøre en test av, heter datafilen for tabellen Versjon (DOKVERSJON - kap. 14.3.3 i Noark-4.1), DOKVER.XML. Den offisielle DTDen for denne tabellfilen heter DOKVERS.DTD. Det vanligste (for de fleste leverandørene?), antar jeg er at tabellfilene har samme navn som tilhørende DTD, da med endelsen XML. Spesielt for uttrekk produsert fra DocuLive av Tieto, forekommer avvik mellom DTD-navnet og tilhørende tabellfil. For eksempel heter filen med metadata om sakene SAK.XML, mens DTDen heter NOARKSAK.DTD.
Det er ingen krav i Noark-4.1 til hva tabellfilene skal hete utover krav 15.4 som sier 8+3 tegn i uppercase. I NOARKIH er det et element som angir hva selve filen heter, noe som åpner for avvikende  bruk av filnavn utover hva DTDene heter, uten at det behøver å være et problem. Jeg antar at noe av årsaken til at filnavnene ikke ble kravsatt, var at det skal være mulig å dele opp "store" filer i mindre deler. Jeg håper virkelig ikke oppdeling av XML-filer forekommer, men det har kanskje gjort det? 

Det som ser ut til å forårsake stopp i testingen, er at "DOKVERS.XML" forventes i ControlExtraOrMissingFiles.cs, noe som ikke passer med at filen i dette tilfellet heter DOKVER.XML.
Det blir ikke generert testrapport.

**Comment by PetterBAR** [comment]
Bare to kommentarer til det jeg skrev tidligere.

1. Bekymringen min om oppdeling av filer, ser ut til å være ubegrunnet. I Riksarkivarens forskrift står det følgende:
"§ 5-31.Organisering av datafiler i avleverings- eller deponeringspakke
(1) Filene som utgjør arkivuttrekket, skal være organisert på følgende måte:
a)	Arkivuttrekk skal ligge på første nivå under rotkatalogen på vedkommende lagringsenhet. Filnavn skal være entydige, og ha filendelsen DAT når formatet er fast eller tegnseparert, og XML når formatet er XML. Det skal brukes et lagringsmedium hvor filer ikke må deles."
Det har muligens forekommet oppdeling tidligere?

2. Det er ikke et eksplisitt krav til navnet på de to obligatoriske rapportene Journal og Saks- og dokumentoversikt, men i Noark-4-standarden står det følgende:
"15.3.2 Generelt om rapportformatet
Rapportene skal tas ut i XML-format. De to rapportene som skal avleveres bør gis
filnavnene JOURNAL.XML og SAKDOK.XML."
Videre står det noe om oppdeling av store rapportfiler, men det blir som sagt ikke aktuelt fremover.

**Comment by PetterBAR** [comment]
En kommentar angående rapportene Journal (JOURNAL.XML) og Saks- og dokumentoversikt (SAKDOK.XML).
NOARKIH.XML er ikke designet for å inneholde informasjon om disse rapportene. Siden Arkade 5 sin behandling av Noark-4-uttrekk baserer seg på transformasjon av NOARKIH.XML til addml.xml med et sett prosesser, betyr dette at slik testopplegget er nå, vil ikke rapportene bli testet. Hvordan er det for eksempel tenkt at rapportene skal kunne valideres mot aktuelle DTDer?

**Comment by PetterBAR** [comment]
Er det noen planer om å endre løsningen med hardkodet "DOKVERS.XML" i ControlExtraOrMissingFiles.cs slik at det ikke er nødvendig å justere uttrekket hvor for eksempel "DOKVER.XML" er brukt for å få gjennomført testen av Noark-4-uttrekk?

**Comment by erikaaberg** [comment]
Noark 4 testing utgår. Vi kastet inn håndkleet.
