### ISSUE TITLE
Noark-4 - Arkade tester på fremmednøkler med felt som ikke skal med i uttrekk

### ISSUE THREAD

**Issue by PetterBAR** [arkivverket/arkade5#81]
Arkade 1.0.5.90
Arkade melder om "Missing ADDML definition object ..." for felt som ikke skal med i uttrekk, dvs. at de står i kursiv i kravtabellen. For uttrekk er det unødvendig å definere slike fremmednøkler, og teste på dem.
Se vedlagte skjermdumper for mer info.
![addml_journalpost](https://user-images.githubusercontent.com/21096792/34410248-0804769c-ebcf-11e7-90f3-6dfb5b7489fe.PNG)
![n_4_1_2_jp](https://user-images.githubusercontent.com/21096792/34410249-08ca9d04-ebcf-11e7-8e22-f2625fdbf531.PNG)
![relasjonsfeil_jp_1](https://user-images.githubusercontent.com/21096792/34410250-08e95596-ebcf-11e7-9b8f-60711f391f48.PNG)

**Comment by erikaaberg** [comment]
Ikke lenger relevant. Arkade kaste inn håndkleet når det gjaldt skikkelig testing av Noark 4 uttrekk.
