### ISSUE TITLE
Forhåndsutfylling i arkivpakkevinduet

### ISSUE THREAD

**Issue by eivinddillevig** [arkivverket/arkade5#82]
Jeg leser i dokumentasjonen at det skal være mulig å forhåndsutfylle arkivpakkevinduet ved å lagre en mets-fil med metadataene i. fra dokumentasjon: 
"Arkade vil forsøke å lese inn eventuelle eksisterende metadata, fra en mets.xml-fil i arkivuttrekket, og forhåndsutfylle feltene i arkivpakkevinduet". 

Jeg har ikke klart å få dette til, og lurer på om det er mulig å få et eksempel på hvordan denne filen ser ut, hva den heter og hvor jeg kan legge den i pakken for å få det til å fungere.

**Comment by joafug** [comment]
Hei

Dette har av ulike årsaker ikke blitt prioritert. Nå som vi har en konkret forespørsel forøker vi å få dette med til neste utgivelse, men kan ikke love noe. 

Joachim

**Comment by erikaaberg** [comment]
Dette er gjort. Eksempelfil kan lag(r)es fra og med kommende versjon 2.7.
