### ISSUE TITLE
Rapporte feil må vise til raden som inneholder feil / mangel

### ISSUE THREAD

**Issue by SteinarAbrahamsen** [arkivverket/arkade5#83]
Det må være mulig å finne referanse til objektet som feilen er relatert til

Brukeren av testverktøyet vil da kunne
1) Avgjøre om det er en feil
2) Rette / endre egenskaper i datagrunnlaget.

**Comment by erikaaberg** [comment]
Dette anses som løst. Ref. Jira #581, rettet i versjon 2.6.0.
