### ISSUE TITLE
Utgått saker og journalposter må ingnoreres

### ISSUE THREAD

**Issue by SteinarAbrahamsen** [arkivverket/arkade5#84]
Det er krav om at et avleveringsuttrekk skal inneholde utgåtte saksmapper og journalposter. Utgåtte registreringer er naturlig nok beheftet med feil og mangler. 

Dette medfører et testresultat som er villedende.

**Comment by erikaaberg** [comment]
Til vurdering - ref. Jira 597 og 244 - kan være noe omfattende.

**Comment by erikaaberg** [comment]
Utført i versjon 2.9.0.
