### ISSUE TITLE
Småting i nyeste bygg

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#86]
Dette er også ting som henger igjen fra tidligere, så ikke nødvendigvis nye ting:

Generelt: I de tilfelle hvor rapporten melder om "xxx flere feil av samme type" og dette faktisk er feil som av en eller annen grunn burde ligge til grunne for avvisning av uttrekke, bør det komme noe mere forklaring på hva feilen går ut på, kan forårsake av følgefeil e.l. Ikke lett for en leverandør/kommuene/IKA å nødvendigvis se alvorlighetsgrad ved rapportering av feil i rapporten når det kun står kryptiske feilregistreringer som "Arkivdel (systemID): 6163a43b-6889-496c-a1d2-03b254b40511 - Klasse (systemID): 715e6a5a-fb2f-4b6f-8270-e893d71ef64f - Antall: 1". Hva er feil, og hvorfor er dette ansett som feil? Og jada, må jo sikkert kunne forvente at man leser test-spesifikasjoner, men disse bør i såfall være lenket opp i rapporten, slik at man enkelt kan klikke videre til "Les mer om denne testen" eller noe slikt.. 

En annen ting er at i de tilfeller hvor det kommer rader i rapporten som er ansett som "feil", så bør dette fremgå av rapporten. I dag er det kun hvis det er flere enn 100 feil (altså at det kommer "xxx flere feil av samme type") at det gis noen som helst pekepinn på om radene som det informeres om faktisk er ansett som info, feil eller noe annet..

Andre småting:
N5.14 - Første melding (oppsummering av total) mangler ledetekst (kun tall)
N5.23 - Første melding (oppsummering av total) mangler ledetekst (kun tall)
N5.24 - Første melding (oppsummering av total) mangler ledetekst (kun tall)
N5.26 - Første melding (oppsummering av total) mangler ledetekst (kun tall)
N5.27 - Første melding (oppsummering av total) mangler ledetekst (kun tall)
N5.29 - I listen over "Antall ulike dokumentformater" informeres det først om antall av forskjellige dokumentformater, og deretter listes det ut filer som ikke er i riktig format. Det burde være et mer synlig skille på disse linjene, dvs. ha et mellomrom eller noe i lista, eller en ledetekst når listen over format-mislighold vises, og at totalen i bunn "x flere resultater av samme type." bør være spesifisert at dette gjelder format-mislighold, og ikke totalt blandet med både opptelling og mislighold. Antallet filer med feil i bør ikke blandes med antallet innføringer i rapporten av hver enkelt dokumentformat.
N5.35 - Første melding (oppsummering av total) mangler ledetekst (kun tall)
N5.39 - Første melding (oppsummering av total) mangler ledetekst (kun tall)

Ser ut til at dette med oppsummering av total som mangler ledetekst er noe som går igjen for de fleste tester, så sikkert greit å få det med i alle. Da uttrekket jeg hadde å teste med selvfølgelig ikke gir utslag på alle tester.

Ellers ser dette veldig bra ut :)

**Comment by erikaaberg** [comment]
Ikke lenger relevant. Forbedret i nyere versjoner.
