### ISSUE TITLE
Mer info om uttrekket

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#87]
Hadde det vært mulig å få inn litt mer info i testsammendraget? Slik at man ved å åpne en testrapport får beskjed om hva slags rapport dette er?
I dag får jeg 
Uuid | f3c59396-0b2a-4658-b27d-3c0c06edb146
Arkivtype | Noark5
Tidspunkt for testing | 17. august 2018
Antall filer som er prosessert | 1
Antall avvik funnet | 275141

Dette sier meg i utgangspunktet lite, hvis jeg kun ser denne rapporten uavhengig av mappestruktur/kontekst, og ikke nødvendigvis har førstehåndskunnskap om hvilken kommune/system/periode uttrekket testen baserer seg på.

Hadde det vært en ide å løfte arkivskaper / systemtype / systemnavn / arkivperiode (fra arkivuttrekk.xml) til testsammendrag-feltet?

**Comment by joergen-vs** [comment]
Mener du context.systemName eller context.archive? systemnavn har en større sjanse til å være oppdiktet, "ARKIVSYSTEM" eller forkortelser, mens arkivnavnet vil være "XXX-register", "XXXs sak og personalarkiv".

**Comment by smult** [comment]
Ikke så mye formening om akkurat det, bare at det hadde vært fint å fått med noe informasjon fra arkivuttrekk.xml i rapporten (hvis dette er tilstede selvfølgelig), så det er lettere å avgjøre hvilket uttrekk rapporten tilhører. Vet den normalt sett ligger i mappestruktur/pakke, men av og til kan den opptre som fristillt fil (i forhold til oversendelse til kommune/uttrekkstaker) for verifisering eller kommentarer. Da er det enklere identifisere hvilket uttrekk rapporten gjelder, hvis det finnen noen form for info/identifikator annet en en generert UUID.

Om teksten i systemnavn er generert vil jo dette da gi utslag i rapporten, og sånn sett informere uttrekksinstans om at kanskje dette burde fylles riktig ut, for at rapporten skal se litt bedre ut.

**Comment by smult** [comment]
Ikke sikkert dette er noe problem for de fleste, men synes i alle fall det kan stå på liste over mulige forbedringer av rapporten. :)

**Comment by joafug** [comment]
Hei

Vi har allerede lagt inn arkivskaper og arkivperiode som kommer i neste utgivelse. Vi forsøker å få med  systemtype / systemnavn også til neste utgivelse. Med mindre vi støter på uventede problemer, skulle det gå bra.
