### ISSUE TITLE
Opptelling av antall feil..?

### ISSUE THREAD

**Issue by smult** [arkivverket/arkade5#89]
Stusser litt over opptellingen av antall feil i rapporten i siste bygget:

![image](https://user-images.githubusercontent.com/1849298/47844649-31488e80-ddc3-11e8-81e8-0cf3aa56e7fc.png)

Antall avvik funnet er 132349, mens summen av avvik i listen under er 132186. Et avvik på 163..
Hvor er disse 163 feilene..? Og er dette viktige eller uviktige avvik? Er det forskjell på hva som dukker opp i oppsummeringen øverst?

**Comment by smult** [comment]
Veldig fint å få dette på plass noenlunde kjapt, da tallene som står i rapporten blir gjenstand for forvirring når dette skal presenteres til kommunen som har sendt inn uttrekket. Vanskelig å forklare på en fornuftig måte hvorfor en opptelling ikke fungere. Enten ta ut de som ikke burde vært telt med i totalen, eller inkluder hvorfor tallet er så mye høyere enn en opptelling av antall feil skulle tilsi i rapporten.

**Comment by erikaaberg** [comment]
Fixet.
