### ISSUE TITLE
Tilbakemelding ved opprettelse av SIP

### ISSUE THREAD

**Issue by palm72** [arkivverket/arkade5#9]
Når jeg oppretter en SIP fra et Noark-4 uttrekk ved hjelp av Arkade 5 versjon 0.5.7.0 brukte min maskin 7 minutter. I denne tiden fikk jeg ingen tilbakemeldinger på hva som skjedde, men en beskjed om at applikasjonen ikke svarer. Vi trenger bedre tilbakemelding underveis ved produksjon av SIP.

**Comment by joafug** [comment]
Denne står på gjøremålsliste

Ref: Arkade-138
