### ISSUE TITLE
Liten bug i "Hent eksterne metadata" ved import av en info.xml

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/arkade5#91]
Arkade 5 v1.3.0.0 leser med suksess eksisterende info.xml produsert av Arkade 5 v1.2.2.0 og 1.3.0.0, men med en liten feil:

System \ Versjon får verdi fra Type (eks. "Noark5")
System \ Type blir tom.

Uttrekkssystem \ Versjon får verdi fra Type (eks. "Noark5")
Uttrekkssystem \ Type blir tom.

**Comment by joafug** [comment]
Takk for tilbakemeldingen. Bug er lagt inn i backlog. ARKADE-301

**Comment by erikaaberg** [comment]
Fixet.
