### ISSUE TITLE
Test av fagsystem - Absolutt filsti til datafil gir feilmelding

### ISSUE THREAD

**Issue by PetterBAR** [arkivverket/arkade5#93]
Arkade 5 versjon 1.3.2

Når absolutt filsti oppgis i <flatFile> - <property name="fileName">, melder Arkade 5 tilbake om at filen "Finnes i ADDML, men ikke i arkiv". På tross av dette ser Arkade 5 ut til å lese datafilen.
Når relativ filsti (kun navn og i forhold til addml.xml) oppgis, kommer det ingen feilmelding og filen ser ut til å bli lest på samme måte som ved absolutt filstiangivelse.

Er det meningen at det skal være noen forskjell på absolutt og relativ filstiangivelse?

**Comment by erikaaberg** [comment]
Vi mistenker at feilen ikke skyldes absolutt/relativ filsti i dette tilfelle. Det er en nå verifisert bug at ved "sjekk om finnes" så tolkes filnavn case sensitivt. Mens ved "les fil" tolkes det ikke-case-sensitivt. Vi retter dette - og ser om det hjelper.

**Comment by erikaaberg** [comment]
Dette er løst, ref Jira  356 0g 605. Løst i versjon 2.6.0.
