### ISSUE TITLE
Har noe skjedd med "Angivelse av prosesser for flate filer #29"?

### ISSUE THREAD

**Issue by PetterBAR** [arkivverket/arkade5#94]
Arkade 5 versjon 1.3.2

Har det blitt gjort noe med filangivelsen i prosessene for fagsystemtest?
Jeg kan ikke finne noe om det i dokumentasjonen, noe som i følge kommentar til issue'en skulle legges til.

**Comment by erikaaberg** [comment]
Det er i utgangspunktet ikke mulig å definere prosesser i ADDML-en per fil. Dette må vi leve med. Se også GitHub #93.
