### ISSUE TITLE
Ønske om test av tomme filer

### ISSUE THREAD

**Issue by erikaaberg** [arkivverket/arkade5#95]
For alle typer uttrekk: Advarsel hvis en fil er tom (0 bytes). For Noark 5 - der dokumentobjektet også angir filstørrelse - sjekk overensstemmelse med angitt størrelse - advarsel hvis feil.

**Comment by petterreinholdtsen** [comment]
Gir det mening å arkivere tomme filer?  Ser at tjenestegrensesnittet tilsynelatende tillater det, men er usikker på om det noen gang gir mening.  F.eks. er det jo umulig å fastslå formatet på en tom fil.

**Comment by palm72** [comment]
> Gir det mening å arkivere tomme filer? Ser at tjenestegrensesnittet tilsynelatende tillater det, men er usikker på om det noen gang gir mening. F.eks. er det jo umulig å fastslå formatet på en tom fil.

Nei, jeg er enig i at tomme filer ikke gir mening. Derfor vil det være viktig å identifisere dokumentfiler som kommer tomme i et uttrekk. Dessverre har vi oppdaget en del PDF-konvertering som har feilet og resultert i filer med reell størrelse 0. Filene lå i uttrekket med korrekt sjekksum men med feil angivelse av filstørrelse. XML-filen ga derfor ingen indikasjon på at det var manglende dokumentinnhold. Testen bør returnere en liste over dokumenter som kanskje kan reddes ved å foreta en ny dokumentkonvertering eller fungere som en dokumentasjon av dokumenttap.

Testen bør identifisere dokumentet slik at en raskt kan gjøre oppslag i produksjonssystemet. Det bør også være filtrert slik at mapper og registreringer med status "Utgår" eller som er "Kassert" utelates.

**Comment by erikaaberg** [comment]
Til vurdering. Ref. Jira 355.

**Comment by aneamu** [comment]
Lagt til i 2.10.0
