### ISSUE TITLE
Noark-5 test: Opptelling av møtesaker gir 0 treff

### ISSUE THREAD

**Issue by palm72** [arkivverket/arkade5#96]
Arkade 5 versjon 1.3.2 finner alltid 0 møtemapper - selv når de er tilstede i uttrekket.

**Comment by joergen-vs** [comment]
![image](https://user-images.githubusercontent.com/10667652/55155643-333b3180-5158-11e9-8051-b049f0946560.png)
Funksjonen er oppdatert, vil være med i neste utgave.
