### ISSUE TITLE
Noark 5-test 29 - Feilrapportering av Format-misforhold?

### ISSUE THREAD

**Issue by PetterBAR** [arkivverket/arkade5#97]
Arkade 5 versjon 1.3.2

N5.29 - Antall dokumenter i arkivuttrekket fordelt på dokumentformat

Det ser ut til at det blir rapportert om "Format-misforhold" når format-elementet i dokumentobjekt i arkivstruktur.xml inneholder uppercase-bokstaver og filendelsen i filnavnet er i lower.
Eksempel: "Dokumentformat: PDF" - filendelse: *.pdf

**Comment by erikaaberg** [comment]
Notert. Lagt inn i Jira for oppfølging.

**Comment by petterreinholdtsen** [comment]
Er dette samme utfordring som i #118?

**Comment by sturtzel** [comment]
Delvis. Selv om det i UNIX-verdenen stort sett er case sensitivitet er det ikke slik i Windowsverdenen. Store og små bokstaver som filending går om hverandre.

**Comment by petterreinholdtsen** [comment]
[Ragnar Sturtzel]
> Delvis. Selv om det i UNIX-verdenen stort sett er case sensitivitet er
> det ikke slik i Windowsverdenen. Store og små bokstaver som filending
> går om hverandre.

Enig i det, men selv på Windows har filnavnene enten store eller små
bokstaver, og hvis en fil har filending 'pdf', så heter jo filen noe som
slutter med 'pdf', ikke noe som slutter på f.eks. 'PDF'.  Selv om en kan
få treff på søk etter *.PdF, så er det ikke uklart hva filen faktisk
heter og hvilken endelse som er del av dette navnet.

Forstår jeg denne mangelmeldingen riktig i at #97 handler om at Arkade
forsøker å koble filending og verdien i <format>, og ikke forstår at
fil.pdf og FIL.PDF begge kan ha formatkode 'PDF'?  Det er veldig nært
problemstillingen i mangelmelding #118, som handler om at Arkade
forsøker å håndheve og begrense verdivalg på innholdet i format-feltet
uten at det eksisterer en katalog over gyldige feltverdier.

Gitt status på liste over formatkoder omtalt i Noark 5-spesifikasjonene
(det mangler helt), så virker det klart at Arkade ikke har noe grunnlag
for å håndheve en forventning om kobling mellom filnavn og
format-verdier.

Det blir bedre når Noark 5-spesifikasjonen blir oppdatert med en liste
over formatkoder som skal brukes og hva de betyr.  Jeg gleder meg til
listen med PRONOM-koder blir klar. :)

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by erikaaberg** [comment]
Løst i versjon 1.5.0.

**Comment by sturtzel** [comment]
@erikaaberg Løst på hvilken måte? At format ikke lenger valideres eller at kun case ignoreres?

**Comment by erikaaberg** [comment]
Fra vår spisskompetanse kopierer jeg noen kommentarer her:

Format fortsetter å valideres, med lower-case.
 - - -
Vi tror testen er nyttig da	det kan forenkle vedlikehold / konvertering hos depot med flere detaljer om hvilke filformater som er bevart. Det gir en bedre validering av dokumenter, utover ren eksistens og sjekksum.
- - -
Ang. Noark spec.: Den er ikke endret, men, men forståelsen av feltet Format har alltid vært vagt. Det har vært fritekst (RA-PDF) men også foreslått å være mime-type. Men «når man følger standarden, skal format-feltet inneholde en PUID, eller pronom-id, hentet ‘fra pronom-registeret over formater fra det britiske nasjonalarkivet’». 
Ref. https://github.com/arkivverket/noark5-standard/blob/master/kapitler/030-noark-5-datamodell.rst#:~:text=Verdier%20i%20formatfeltene%20(M701%2C%20M712%2C%20M713)
- - -
Arkade tester i dag «fileExtension.Equals($".{Format}")» eller «’.pdf’ er lik ‘.pdf’, mens Noark-standarden legger opp til en validering mot PRONOM. Så essensielt resultatet fra filanalysen mot verdi i format-feltet. Er dette realistisk eller ikke....  Siden godkjenning av arkivløsninger i dag fremdeles bruker <format>pdf</format>, så legger vi foreløpig ikke mer arbeid i testen [til det er avklart]. 
- - -
Se også https://github.com/arkivverket/noark5-standard/blob/master/kapitler/110-vedlegg_1_metadatakatalog-auto.rst#:~:text=Navn-,format,-Datatype
- - -

**Vi håper dette kan være med på å avklare.**

**Comment by sturtzel** [comment]
Beskrivelsen i github samsvarer ikke med versjon 5.5.0 på hjemmesiden: https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden

Der sies det at M701 etc. skal bestemmes senere og det er ingen referanser til github.

Slik endring av standarden må tas som en revisjon av standarden der endringene er dokumentert, og ikke "snikinnføres" via tekst i github.

Bruk av Pronom krever en inngående kjennskap til dokumentformater. Bare .pdf har 39 forskjellige definisjoner. Formater som .docx har tre, .sos fem, .jpeg ni.

**Comment by sturtzel** [comment]
Det er mulig å følge PDF-kravene uten at arkivkjernen vet hvilken versjon av PDF som ligger i filene. Dette gjøres ved konfigurering i eksterne verktøy som tar diverse formater inn og sender PDF/A ut.

M701 inngår i dag i integrasjoner mellom arkivet og et utall fagsystemer gjennom integrasjonsstandarder som GeoIntegrasjon og etter hvert Fiks Arkiv. En endring i spesifikasjonen kan derfor ha store konsekvenser. Som sagt: Denne typen endringer krever bredere behandling enn et issue eller en PR i github.

Formatfeltet gjelder også for produksjonsformatene, ikke kun for avleveringen.

**Comment by sturtzel** [comment]
Det refereres til tidligere formidling fra Arkivverket. Sist publiserte versjon av Noark 5 er versjon 5.5.0 og det er ingen info derfra om at denne ikke lenger gjelder.

Jeg får ikke hentet formuleringene fra hjemmesiden til Arkivverket da alle Noark-artikler ender opp i "Finner ikke siden". Unntaket er oversikten https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden

**Comment by sturtzel** [comment]
Da er hjemmesidene oppe igjen hos Arkivverket: https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark5-standarden har ingen informasjon om endringer etter 18. desember 2018, sier at versjon 5.0 er gjeldende og ingen lenke til github om det er stedet man nå publiserer endringer i standarden!

Basert på det kan jeg ikke se at det er grunnlag for å si at det er formidlet endringer. Da må som et minimum denne siden oppdateres. Pronon er en så inngripende endring at den burde vært sendt på høring. Evt. burde Arkade tatt jobben med å bygge denne informasjonen som ledd i å lage avleveringspakke.

**Comment by petterreinholdtsen** [comment]
Jeg har sjekket epostarkivet mitt, og ser at første gang jeg ble fortalt
at formatfeltet skulle inneholde PRONOM-koder var i 2019, se for
eksempel melding 2019-01-21 fra Hans Fredrik Berg i
<URL: https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/issues/11 >
og melding 2019-03-01 fra samme Arkivverket-ansatte i
<URL: https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/issues/4 >.
Tilsvarende beskjeder har jeg fått fra Arkivverket flere ganger etter
dette.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by sturtzel** [comment]
Men dette er diskusjoner i et repo som fordrer at man har abonnert på alle hendelser i dette for å få det med seg.

En leverandør som skal implementere et Noark-arkiv vil forholde seg til standarden slik den er spesifisert. Den har ingen henvisning til repoet for presiseringer/endringer. Som et minimum måtte det ha vært en liste over endringer så folk ikke måtte lese gjennom potensielt hundrevis av issues i et repo for å vite hvordan standarden p.t. er. Er denne endringen Noark 5 versjon 5.1? 5.0 har ikke noe slikt krav.

**Comment by petterreinholdtsen** [comment]
[Ragnar Sturtzel]
> Men dette er diskusjoner i et repo som fordrer at man har abonnert på
> alle hendelser i dette for å få det med seg.

Jeg tror du misforstår poenget mitt.  Jeg forsøker ikke å dokumentere at
budskapet er spredt vidt og bredt, men at budskapet har sin kilde hos
Arkivverket.  Jeg vet bare hva jeg selv har fått med meg, ikke hva
Arkivverket har kommunisert til andre.

-- 
Vennlig hilsen
Petter Reinholdtsen
