### ISSUE TITLE
Entydig systemID og N5.62 - Kontroll av referansene i endringsloggen

### ISSUE THREAD

**Issue by PetterBAR** [arkivverket/arkade5#99]
Arkade 5 versjon 1.4.0
N5.62 - Kontroll av referansene i endringsloggen

Vi har et arkivuttrekk hvor systemID i arkivstruktur.xml ikke er entydig.
Test N5.62 rapporterer at ingen feil er funnet.

Siden det i praksis er snakk om et "en-til-mange"-forhold mellom arkivstruktur.xml og endringslogg.xml, burde ikke (eller gjør den allerede?) testen ta hensyn til at samme systemID kan forekomme i arkivstruktur.xml for en endring i endringslogg.xml?

**Comment by erikaaberg** [comment]
Test 62 skal være mer "finner jeg  denne referansen fra endringsloggen igjen i arkivstruktur?". Feil når den ikke finnes, korrekt når den finnes. Test på unik systemID er egen test.
